@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">

		<!-- order creation modal -->
		@if ($controlSwitch['warehouse-order-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.warehouse_order'))
		@endif

		@if ($controlSwitch['warehouse-transaction-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.warehouse_transaction'))
		@endif

		@if ($controlSwitch['warehouse-order-window'])
			<div id="inboundbookingwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Incoming order') }}</h4></td>
							<td>
							@if ($controlSwitch['create-order-button'])
								<button type="button" class="btn btn-info pull-right" onclick="createWarehouseOrderInModal('receive')" >{{ trans('warehouse.New incoming order') }}</button>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="inboundbookingtable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if (false /* $controlSwitch['warehouse-order-window'] */)
			<div id="transferwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Transfer') }}</h4></td>
							<td>
								<button class="btn btn-info pull-right" >{{ trans('warehouse.New transfer order') }}</button>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="transfertable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['warehouse-order-window'])
			<div id="pickinglistwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Outgoing order') }}</h4></td>
							<td>
							@if ($controlSwitch['create-order-button'])
								<button class="btn btn-info pull-right" onclick="createWarehouseOrderInModal('deliver')" >{{ trans('warehouse.New outgoing order') }}</button>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="pickinglisttable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Document') }}</th>
								<th>{{ trans('forms.Item count') }}</th>
								<th>{{ trans('forms.Label') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Process date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['inventory-window'])
			<div id="inventorywindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Inventory') }}</h4></td>
							<td align='right'>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="inventorytable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Bin') }}</th>
								@if (auth()->user()->can('wo-view'))
									<th></th>
								@endif
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.Bin') }}</th>
								@if (auth()->user()->can('wo-view'))
									<th></th>
								@endif
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['report-window'])
			<div id="reportwindow" class="panel panel-default">
				<div class="panel-heading"><h4>{{ trans('messages.Report') }}</h4></div>

				<div class="panel-body">
				@if ($controlSwitch['inventory-report'])
					<a href="{{ url('warehouse/inventory/print?date=' . \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d"))) }}" class="btn btn-sq-lg btn-info" ><span class="fa fa-2x fa-question-circle"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Inventory report")) !!}</a>
				@endif
				@if ($controlSwitch['aging-report'])
					<a href="{{ url('warehouse/aging') }}" class="btn btn-sq-lg btn-info" ><span class="fa fa-2x fa-question-circle"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Aging inventory")) !!}</a>
					<!-- <a class="btn btn-sq-lg btn-info" disabled><span class="fa fa-2x fa-question-circle"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.In-transit inventory")) !!}</a> -->
				@endif
				</div>
			</div>
		@endif

		@if ($controlSwitch['tool-window'])
			<div id="toolwindow" class="panel panel-default">
				<div class="panel-heading"><h4>{{ trans('messages.Tool') }}</h4></div>

				<div class="panel-body">
				@if ($controlSwitch['generate-label-button'])
					<a href="{{ url('warehouse/label') }}" class="btn btn-sq-lg btn-info"><span class="fa fa-2x fa-barcode"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Generate label")) !!}</a>
				@endif
				@if ($controlSwitch['manage-bin-button'])
					<a href="{{ url('warehouse/bins') }}" class="btn btn-sq-lg btn-info"><span class="fa fa-2x fa-cube"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Bin management")) !!}</a>
				@endif
				</div>
			</div>
		@endif

		</div>
	</div>
</div>

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
	<li style="text-align:center;"><b>{{ trans('messages.Quick scroll menu') }}</b></li>
	<li class="divider"></li>
@if ($controlSwitch['warehouse-order-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#inboundbookingwindow').offset().top}, 500);">{{ trans('warehouse.Incoming order') }}</a></li>
@endif
@if (false /* $controlSwitch['warehouse-order-window'] */)
	<!-- <li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#transferwindow').offset().top}, 500);">{{ trans('warehouse.Transfer') }}</a></li> -->
@endif
@if ($controlSwitch['warehouse-order-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#pickinglistwindow').offset().top}, 500);">{{ trans('warehouse.Outgoing order') }}</a></li>
@endif
@if ($controlSwitch['inventory-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#inventorywindow').offset().top}, 500);">{{ trans('warehouse.Inventory') }}</a></li>
@endif
@if ($controlSwitch['report-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#reportwindow').offset().top}, 500);">{{ trans('messages.Report') }}</a></li>
@endif
@if ($controlSwitch['tool-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#toolwindow').offset().top}, 500);">{{ trans('messages.Tool') }}</a></li>
@endif
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('.container').offset().top}, 500);">{{ trans('messages.Return to top') }}<i style="padding-left:1em;" class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
</ul>

@endsection

@section('post-content')

	<script type="text/javascript" src="{{ asset('js/ContextMenu.js') }}" ></script>

	<script type="text/javascript">

		$(".container").contextMenu({
			menuSelector: "#contextMenu",
			/*
			menuSelected: function (invokedOn, selectedMenu) {
				var msg = "You selected the menu item '" + selectedMenu.text() + "' on the value '" + invokedOn.text() + "'";
				alert(msg);
			}
			*/
		});
	</script>

	<script type="text/javascript" src="{{ asset('js/DataTableHelper.js') }}" ></script>

	<script type="text/javascript" src="{{ asset('js/HtmlTemplateHelper.js') }}" ></script>

@if ($controlSwitch['warehouse-entry-template'])
	<script id="warehouse-entry-template" type="text/x-custom-template">
		<tr id="wo-{id}">
			<td data-order="{title}"><p style="padding-right:2em;display:inline;">{title}</p>
				<i data-condition="{is_prepared}" class="fa fa-check" aria-hidden="true" title="{{ trans('status.Prepared') }}"></i>
				<i data-condition="{is_delivered}" class="fa fa-truck" aria-hidden="true" title="{{ trans('status.Shipped') }}"></i>
				<i data-condition="{is_void}" class="fa fa-ban" aria-hidden="true" title="{{ trans('status.Void') }}"></i>
			</td>
			<td style="text-align:right;">{items}</td>
			<td>{reference}</td>
			<td>{bins_string}</td>
			<td data-order="{delivery_date}">{delivery_date_display}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' onclick="viewWarehouseOrderInModal({id})" title="{{ trans('forms.View') }}"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{is_open} &amp;&amp; !{is_prepared} &amp;&amp; {can_edit}" class='btn btn-info btn-xs' onclick="processWarehouseOrderInModal({id})" title="{{ trans('forms.Process') }}"><i class="fa fa-clipboard" aria-hidden="true"></i></button>
				<button data-condition="{can_void}" class='btn btn-info btn-xs' onclick="voidWarehouseOrderInModal({id})" title="{{ trans('forms.Void') }}"><i class="fa fa-ban" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['inventory-template'])
	<script id="inventory-template" type="text/x-custom-template">
		<tr id="inventory-{location_id}-{sku_id}">
			<td>{sku}</td>
			<td class="text-right">{balance}</td>
			<td>{location}</td>
			<td style="width:50%;">{bins_string}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewWarehouseTransactionInModal({location_id}, {sku_id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['warehouse-order-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#inboundbookingtable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-order/inbound/ajax', { }, '#inboundbookingtable', '#warehouse-entry-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\WarehouseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 4, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#inboundbookingtable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['warehouse-order-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#pickinglisttable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-order/outbound/ajax', { }, '#pickinglisttable', '#warehouse-entry-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\WarehouseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 4, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#pickinglisttable');
			});
		} );
	</script>
@endif

@if (false /*$controlSwitch['warehouse-order-window']*/)
	<script type="text/javascript">
		$(document).ready(function() {
			$('#transfertable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-order/transfer/ajax', { }, '#transfertable', '#warehouse-entry-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\WarehouseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 4, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#transfertable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['inventory-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#inventorytable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-inventory/ajax', { }, '#inventorytable', '#inventory-template', '{{ trans('tool.Enter search keyword') }}', '', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 3 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#inventorytable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['warehouse-entry-template'])
	<script type="text/javascript">
		function refreshTableWithOrder(data, is_new) {
			// insert/update result back to table
			let content = populateHtmlTemplateWithData($('#warehouse-entry-template').html().toString(), data['order']);
			switch (data['order']['type']) {
				case "receive":
					if (!is_new) {
						$('#inboundbookingtable').DataTable().row('#wo-' + data['order']['id']).remove();
					}
					$('#inboundbookingtable').DataTable().row.add($(content)).draw();
					break;
				case "relocate":
					break;
				case "transfer":
					if (!is_new) {
						$('#transfertable').DataTable().row('#wo-' + data['order']['id']).remove();
					}
					$('#transfertable').DataTable().row.add($(content)).draw();
					break;
				case "deliver":
					if (!is_new) {
						$('#pickinglisttable').DataTable().row('#wo-' + data['order']['id']).remove();
					}
					$('#pickinglisttable').DataTable().row.add($(content)).draw();
					break;
			}

			// inventory table update.
	    for (index in data['inventory']) {
				let content = populateHtmlTemplateWithData($('#inventory-template').html().toString(), data['inventory'][index]);
				$('#inventorytable').DataTable().row('#inventory-' + data['inventory'][index]['location_id'] + '-' + data['inventory'][index]['sku_id']).remove();
				$('#inventorytable').DataTable().row.add($(content));
	    }
			$('#inventorytable').DataTable().draw();

		  // bin location might changed because of this.  Re-source
		  for (productKey in warehouseOrderDataSource.products) {
		    warehouseOrderDataSource.products[productKey]['bins']['deliver'] = data['bin_availability'][warehouseOrderDataSource.products[productKey]['id']];
		  }
		}
	</script>
@endif

@if ($controlSwitch['warehouse-order-modal'])
	<script type="text/javascript">
		function warehouseOrderDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// source for product selection
			warehouseOrderDataSource.products = {
			@php
				$receiveBins = \App\WarehouseBin::getBinIndexedByUniqueTradableAndLocation("receive");
				$deliverBins = \App\WarehouseBin::getBinIndexedByUniqueTradableAndLocation("deliver");
			@endphp
			@foreach (\App\UniqueTradable::getActiveProducts('id', 'asc') as $uniqueTradable)
				"{{ $uniqueTradable->sku }}" : {
					id : "{{ $uniqueTradable->id }}",
					sku : "{{ $uniqueTradable->sku }}",
					description : "{{ $uniqueTradable->description }}",
					bins : {
						receive : {!! json_encode($receiveBins[$uniqueTradable->id]) !!},
						deliver : {!! json_encode($deliverBins[$uniqueTradable->id]) !!}
					}
				},
				@if ( !empty($uniqueTradable->product_id) )
					"{{ $uniqueTradable->product_id }}" : {
						id : "{{ $uniqueTradable->id }}",
						sku : "{{ $uniqueTradable->sku }}",
						description : "{{ $uniqueTradable->description }}",
						bins : {
							receive : {!! json_encode($receiveBins[$uniqueTradable->id]) !!},
							deliver : {!! json_encode($deliverBins[$uniqueTradable->id]) !!}
						}
					},
				@endif
			@endforeach
			};
			// text for 'Submit' button
			warehouseOrderDataSource.button_create_order = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// text for 'Update' button
			warehouseOrderDataSource.button_void_order = "<i class=\"fa fa-btn fa-ban\"></i>" + "{{ trans('forms.Void') }}";
			// title text for new order
			warehouseOrderDataSource.newOrderType = {
				receive  : "{{ trans('warehouse.New incoming order') }}",
				relocate : "{{ trans('warehouse.New transfer order') }}",
				transfer : "{{ trans('warehouse.New transfer order') }}",
				deliver  : "{{ trans('warehouse.New outgoing order') }}"
			};
			// callback function when new order is submitted
			warehouseOrderDataSource.insertCallback = function(data) {
				refreshTableWithOrder(data, true);
			};
			// callback function when order is updated
			warehouseOrderDataSource.updateCallback = function(data) {
				refreshTableWithOrder(data, false);
			};

		});
	</script>
@endif

@if ($controlSwitch['warehouse-order-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/warehouse_order.js') }}"></script>
@endif

@if ($controlSwitch['warehouse-transaction-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/warehouse_transaction.js') }}"></script>
@endif

@endsection
