@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<!-- purchase-quote form modal -->
		@if ($controlSwitch['purchase-quote-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.purchase_quote'))
		@endif

			<!-- purchase-entry form modal -->
		@if ($controlSwitch['purchase-order-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.purchase_order'))
		@endif

			<!-- warehouse-order form modal -->
		@if ($controlSwitch['warehouse-order-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.pregenerated_warehouse_order'))
		@endif

			<!-- taxable-entity form modal -->
		@if ($controlSwitch['entity-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.taxable_entity'))
		@endif

			<!-- warehouse-transaction modal -->
		@if($controlSwitch['warehouse-transaction-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.warehouse_transaction'))
		@endif

			<!-- charge-entry modal -->
		@if ($controlSwitch['charge-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.charge_entry'))
		@endif

			<!-- supplier-stats modal -->
		@if ($controlSwitch['supplier-stats-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.supplier_stats'))
		@endif

		@if ($controlSwitch['supplier-window'])
			<div id="supplierwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Supplier') }}</h4></td>
							<td align='right'>
						@if ($controlSwitch['create-supplier-button'])
							<input type="button" class="btn btn-primary" onclick="createTaxableEntityInModal('supplier')" value="{{ trans('vrm.New supplier') }}"/>
						@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="suppliertable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Name') }}</th>
								<th>{{ trans('vrm.Code') }}</th>
								<th>{{ trans('vrm.Contact') }}</th>
								<th>{{ trans('vrm.Region') }}</th>
								<th>{{ trans('vrm.Outstanding order') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Name') }}</th>
								<th>{{ trans('vrm.Code') }}</th>
								<th>{{ trans('vrm.Contact') }}</th>
								<th>{{ trans('vrm.Region') }}</th>
								<th>{{ trans('vrm.Outstanding order') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['quote-window'])
			<div id="quotewindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Purchase quote') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-quote-button'])
								<!-- <input type="button" class="btn btn-primary" onclick="window.location.href='{{ url('/vrm/createquote') }}'" value="{{ trans('vrm.New quote') }}"/></td>-->
								<button type="button" class="btn btn-primary" onclick="createPurchaseQuoteInModal()" >{{ trans('vrm.New quote') }}</button>
							@endif
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="quotetable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Purchase quote') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Input date') }}</th>
								<th>{{ trans('vrm.Contact') }}</th>
								<th>{{ trans('vrm.Staff') }}</th>
								<th>{{ trans('vrm.Items') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Purchase quote') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Input date') }}</th>
								<th>{{ trans('vrm.Contact') }}</th>
								<th>{{ trans('vrm.Staff') }}</th>
								<th>{{ trans('vrm.Items') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['order-window'])
			<div id="orderwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Purchase order/return') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-order-return-button'])
								<div class="btn-group">
									<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#" >
										{{ trans('vrm.New entry') }}
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
									@if ($controlSwitch['create-order-button'])
								    <li>
											<a onclick="createPurchaseEntryInModal('order')">{{ trans('vrm.New order')}}</a>
										</li>
									@endif
									@if ($controlSwitch['create-return-button'])
								    <li>
											<a onclick="createPurchaseEntryInModal('return')">{{ trans('vrm.New return') }}</a>
										</li>
									@endif
									</ul>
								</div>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="orderreturntable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Purchase order/return') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Delivery date') }}</th>
								<th>{{ trans('vrm.Staff') }}</th>
								<th>{{ trans('vrm.Balance') }}</th>
								<!-- <th>{{ trans('vrm.Total') }}</th> -->
								<th>{{ trans('vrm.Percent') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Purchase order/return') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Delivery date') }}</th>
								<th>{{ trans('vrm.Staff') }}</th>
								<th>{{ trans('vrm.Balance') }}</th>
								<!-- <th>{{ trans('vrm.Total') }}</th> -->
								<th>{{ trans('vrm.Percent') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to make data-order attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<!-- <td></td> -->
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['inbound-booking-window'])
			<div id="inboundbookingwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Inbound booking') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-booking-button'])
								<!-- <input type="button" class="btn btn-primary" onclick="window.location.href='{{ url('/vrm/createinboundbooking') }}'" value="{{ trans('vrm.New inbound booking') }}"/> -->
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="inboundbookingtable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Purchase order') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Consignee') }}</th>
								<th>{{ trans('vrm.Delivery date') }}</th>
								<th>{{ trans('vrm.Item count') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Purchase order') }}</th>
								<th>{{ trans('vrm.Supplier') }}</th>
								<th>{{ trans('vrm.Consignee') }}</th>
								<th>{{ trans('vrm.Delivery date') }}</th>
								<th>{{ trans('vrm.Item count') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to make 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['outbound-booking-window'])
			<div id="pickinglistwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Picking list') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-picking-button'])
								<!-- <input type="button" class="btn btn-primary" onclick="window.location.href='{{ url('/vrm/createpickinglist') }}'" value="{{ trans('vrm.New picking list') }}"/> -->
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="pickinglisttable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Sales order') }}</th>
								<th>{{ trans('vrm.Customer') }}</th>
								<th>{{ trans('vrm.Operator') }}</th>
								<th>{{ trans('vrm.Input date') }}</th>
								<th>{{ trans('vrm.Item count') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Sales order') }}</th>
								<th>{{ trans('vrm.Customer') }}</th>
								<th>{{ trans('vrm.Operator') }}</th>
								<th>{{ trans('vrm.Input date') }}</th>
								<th>{{ trans('vrm.Item count') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to make 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['charge-window'])
			<div id="chargebackwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('vrm.Supplier chargeback') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-charge-button'])
								<input type="button" class="btn btn-primary" onclick="createChargeEntryInModal()" value="{{ trans('vrm.New chargeback') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="chargebacktable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Customer') }}</th>
								<th>{{ trans('vrm.Incur date') }}</th>
								<th>{{ trans('vrm.Total') }}</th>
								<th>{{ trans('vrm.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('vrm.Document') }}</th>
								<th>{{ trans('vrm.Customer') }}</th>
								<th>{{ trans('vrm.Incur date') }}</th>
								<th>{{ trans('vrm.Total') }}</th>
								<th>{{ trans('vrm.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to make 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['inventory-window'])
			<div id="inventorywindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Inventory') }}</h4></td>
							<td align='right'>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="inventorytable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need a stuffer row in order to make 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['report-window'])
			<div id="reportwindow" class="panel panel-default">
				<div class="panel-heading"><h4>{{ trans('messages.Report') }}</h4></div>

				<div class="panel-body">
					<a class="btn btn-sq-lg btn-info" disabled><span class="fa fa-2x fa-question-circle"></span><br/>{!! str_replace(" ", "<br/>", trans("vrm.Data export")) !!}</a>
				</div>
			</div>
		@endif

		@if ($controlSwitch['tool-window'])
			<div id="toolwindow" class="panel panel-default">
				<div class="panel-heading">
					<h4>{{ trans('messages.Tool') }}</h4>
				</div>

				<div class="panel-body">
					<a href="{{ url('vrm/inventory-alert') }}" class="btn btn-sq-lg btn-info"><span class="fa fa-2x fa-cubes"></span><br/>{!! str_replace(" ", "<br/>", trans("vrm.Inventory alert")) !!}</a>
				</div>
			</div>
		@endif

		</div>
	</div>
</div>

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
	<li style="text-align:center;"><b>{{ trans('messages.Quick scroll menu') }}</b></li>
	<li class="divider"></li>
@if ($controlSwitch['supplier-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#supplierwindow').offset().top}, 500);">{{ trans('vrm.Supplier') }}</a></li>
@endif
@if ($controlSwitch['quote-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#quotewindow').offset().top}, 500);">{{ trans('vrm.Purchase quote') }}</a></li>
@endif
@if ($controlSwitch['order-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#orderwindow').offset().top}, 500);">{{ trans('vrm.Purchase order/return') }}</a></li>
@endif
@if ($controlSwitch['inbound-booking-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#inboundbookingwindow').offset().top}, 500);">{{ trans('vrm.Inbound booking') }}</a></li>
@endif
@if ($controlSwitch['outbound-booking-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#pickinglistwindow').offset().top}, 500);">{{ trans('vrm.Picking list') }}</a></li>
@endif
@if ($controlSwitch['charge-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#chargebackwindow').offset().top}, 500);">{{ trans('vrm.Supplier chargeback') }}</a></li>
@endif
@if ($controlSwitch['inventory-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#inventorywindow').offset().top}, 500);">{{ trans('warehouse.Inventory') }}</a></li>
@endif
	<!-- <li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#allocationwindow').offset().top}, 500);">{{ trans('vrm.Allocation') }}</a></li> -->
@if ($controlSwitch['report-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#reportwindow').offset().top}, 500);">{{ trans('messages.Report') }}</a></li>
@endif
@if ($controlSwitch['tool-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#toolwindow').offset().top}, 500);">{{ trans('messages.Tool') }}</a></li>
@endif
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('.container').offset().top}, 500);">{{ trans('messages.Return to top') }}<i style="padding-left:1em;" class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
</ul>
@endsection

@section('post-content')

@if (!App::environment('local'))
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
@else
	<script type="text/javascript" src="{{ asset('external/ajax/libs/Chart.js/2.7.1/Chart.min.js') }}"></script>
@endif

	<script type="text/javascript" src="{{ asset('js/ContextMenu.js') }}"></script>

	<script type="text/javascript">
		$(".container").contextMenu({
			menuSelector: "#contextMenu",
			/*
			menuSelected: function (invokedOn, selectedMenu) {
				var msg = "You selected the menu item '" + selectedMenu.text() + "' on the value '" + invokedOn.text() + "'";
				alert(msg);
			}
			*/
		});
	</script>

	<script type="text/javascript" src="{{ asset('js/DataTableHelper.js') }}" ></script>

	<script type="text/javascript" src="{{ asset('js/HtmlTemplateHelper.js') }}" ></script>

	<script src="{{ asset('external/imagebox/js/jquery.imagemodal.js') }}"></script>

@if ($controlSwitch['entity-template'])
	<script id="entity-template" type="text/x-custom-template">
		<tr id="entity-{id}">
			<td><p style="padding-right:2em;display:inline;">{name}</p>
				<i data-condition="{is_active}" class="fa fa-heartbeat" aria-hidden="true" title="{{ trans('status.Active') }}"></i>
			</td>
			<td>{code}</td>
			<td>{contact}</td>
			<td>{region}</td>
			<td class="text-right">{outstanding}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewTaxableEntityInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updateTaxableEntityInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="loadSupplierStats({id})"><i class="fa fa-line-chart" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['quote-template'])
	<script id="quote-template" type="text/x-custom-template">
		<tr id="quote-{id}">
			<td data-order="{title}"><p style="padding-right:2em;display:inline;">{title}</p>
				<i data-condition="{is_approved}" class="fa fa-check-square-o" aria-hidden="true" title="{{ trans('status.Approved') }}"></i>
				<i data-condition="{is_valid}" class="fa fa-check-circle" aria-hidden="true" title="{{ trans('status.Valid') }}"></i>
				<i data-condition="!{is_valid}" class="fa fa-times-circle" aria-hidden="true" title="{{ trans('status.Invalid') }}"></i>
			</td>
			<td>{supplier}</td>
			<td data-order="{delivery_date}">{delivery_date_display}</td>
			<td>{contact}</td>
			<td>{staff}</td>
			<td class="text-right">{items}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewPurchaseQuoteInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updatePurchaseQuoteInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
				<button data-condition="{need_approve}" class='btn btn-info btn-xs' title="{{ trans('forms.Approve') }}" onclick="approvePurchaseQuoteInModal({id})"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['order-template'])
	<script id="order-template" type="text/x-custom-template">
		<tr id="purchase-{id}">
			<td data-order="{title}">
				<p data-condition="'{type}' == 'order'" style="padding-right:2em;display:inline;">{title}</p>
				<p data-condition="'{type}' == 'return'" style="padding-right:2em;display:inline;">R{title}</p>
				<i data-condition="{is_approved}" class="fa fa-check-square-o" aria-hidden="true" title="{{ trans('status.Approved') }}"></i>
				<i data-condition="{is_released}" class="fa fa-unlock-alt" aria-hidden="true" title="{{ trans('status.Released') }}"></i>
				<i data-condition="{is_prepared}" class="fa fa-thumbs-o-up" aria-hidden="true" title="{{ trans('status.Prepared') }}"></i>
				<i data-condition="{is_shipped}" class="fa fa-truck" aria-hidden="true" title="{{ trans('status.Shipped') }}"></i>
				<i data-condition="{is_closed}" class="fa fa-archive" aria-hidden="true" title="{{ trans('status.Closed') }}"></i>
				<i data-condition="{is_void}" class="fa fa-ban" aria-hidden="true" title="{{ trans('status.Void') }}"></i>
			</td>
			<td>{supplier}</td>
			<td data-order="{delivery_date}">{delivery_date_display}</td>
			<td>{staff}</td>
			<td class="text-right">{balance}</td>
			<td class="text-right">{percent}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewPurchaseEntryInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updatePurchaseEntryInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
				<button data-condition="{need_approve}" class='btn btn-info btn-xs' title="{{ trans('forms.Approve') }}" onclick="approvePurchaseEntryInModal({id})"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
				<button data-condition="{can_release}" class='btn btn-info btn-xs' title="{{ trans('forms.Release') }}" onclick="purchaseReleasePostAjax('{type}', {id})"><i class="fa fa-unlock-alt" style="padding-left:3px;padding-right:3px;" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['warehouse-entry-template'])
	<script id="warehouse-entry-template" type="text/x-custom-template">
		<tr id="warehouse-{id}">
			<td data-order="{title}"><p style="padding-right:2em;display:inline;">{title}</p>
				<i data-condition="{is_assigned}" class="fa fa-hand-o-left" aria-hidden="true" title="{{ trans('status.Assigned') }}"></i>
				<i data-condition="{is_released}" class="fa fa-unlock-alt" aria-hidden="true" title="{{ trans('status.Released') }}"></i>
				<i data-condition="{is_prepared}" class="fa fa-thumbs-o-up" aria-hidden="true" title="{{ trans('status.Prepared') }}"></i>
				<i data-condition="{is_delivered}" class="fa fa-truck" aria-hidden="true" title="{{ trans('status.Shipped') }}"></i>
			</td>
			<td>{source}</td>
			<td>{entity}</td>
			<td>{operator}</td>
			<td data-order="{delivery_date}">{delivery_date_display}</td>
			<td class="text-right">{items}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewWarehouseOrderInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="processWarehouseOrderInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['charge-template'])
	<script id="charge-template" type="text/x-custom-template">
		<tr id="charge-{id}">
			<td data-order="{title}">{title}</td>
			<td>{entity}</td>
			<td data-order="{incur_date}">{incur_date_display}</td>
			<td class="text-right">{total}</td>
			<td>{status}</td>
			<td>{search-key}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewChargeEntryInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updateChargeEntryInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
				<button data-condition="{can_submit}" class='btn btn-info btn-xs' title="{{ trans('forms.Submit') }}" onclick="submitChargeEntryInModal({id})"><i class="fa fa-file-text" aria-hidden="true"></i></button>
				<button data-condition="{can_retract}" class='btn btn-info btn-xs' title="{{ trans('forms.Retract') }}" onclick="retractChargeEntryInModal({id})"><i class="fa fa-times" aria-hidden="true"></i></button>
				<button data-condition="{can_approve}" class='btn btn-info btn-xs' title="{{ trans('forms.Approve') }}" onclick="approveChargeEntryInModal({id})"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['inventory-template'])
	<script id="inventory-template" type="text/x-custom-template">
		<tr id="tradable-{location_id}-{sku_id}">
			<td>{location}</td>
			<td>{sku}</td>
			<td class="text-right">{balance}</td>
			<td>
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewWarehouseTransactionInModal({location_id},{sku_id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif


@if ($controlSwitch['supplier-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#suppliertable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/entity/supplier/ajax', { }, '#suppliertable', '#entity-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\TaxableEntity::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#suppliertable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['quote-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#quotetable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/purchase-quote/ajax', { }, '#quotetable', '#quote-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\PurchaseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 2, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 7 }, { visible : false, targets : 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#quotetable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['order-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#orderreturntable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/purchase-order/ajax', { }, '#orderreturntable', '#order-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\PurchaseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 2, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 7 }, { visible : false, targets : 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#orderreturntable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['inbound-booking-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#inboundbookingtable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-order/inbound/ajax', { }, '#inboundbookingtable', '#warehouse-entry-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\WarehouseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable : false, targets : 7 }, { visible : false, targets : 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#inboundbookingtable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['outbound-booking-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#pickinglisttable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-order/outbound/ajax', { }, '#pickinglisttable', '#warehouse-entry-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\WarehouseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable : false, targets : 7 }, { visible : false, targets : 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#pickinglisttable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['charge-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#chargebacktable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/expense/supplier/ajax', { }, '#chargebacktable', '#charge-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\ExpenseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 2, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#chargebacktable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['inventory-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#inventorytable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/warehouse-inventory/ajax', { }, '#inventorytable', '#inventory-template', '{{ trans('tool.Enter search keyword') }}', '', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 1, 'asc' ]],
					columnDefs : [{ orderable : false, targets : 3 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#inventorytable');
			});
		} );
	</script>
@endif

@if (false)
	<script type="text/javascript">
		$(document).ready(function() {
			$('#allocationtable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', 'url', { }, '#allocationtable', '#templateSelector', '{{ trans('tool.Enter search keyword') }}', '', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable : false, targets : 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#allocationtable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['quote-template'])
	<script type="text/javascript">
		function refreshTableWithPurchaseQuote(quote, is_new) {
			let content = populateHtmlTemplateWithData($('#quote-template').html().toString(), quote);
			if (!is_new && $('#quotetable').DataTable().row('#quote-' + quote['id']).length) {
				$('#quotetable').DataTable().row('#quote-' + quote['id']).remove();
			}
			$('#quotetable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['order-template'])
	<script type="text/javascript">
		function refreshTableWithPurchaseEntry(entry, is_new) {
			let content = populateHtmlTemplateWithData($('#order-template').html().toString(), entry);
			if (!is_new && $('#orderreturntable').DataTable().row('#purchase-' + entry['id']).length) {
				$('#orderreturntable').DataTable().row('#purchase-' + entry['id']).remove();
			}
			$('#orderreturntable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['entity-template'])
	<script type="text/javascript">
		function refreshTableWithEntity(entity, is_new) {
			let content = populateHtmlTemplateWithData($('#entity-template').html().toString(), entity);
			if (!is_new && $('#suppliertable').DataTable().row('#entity-' + entity['id']).length) {
				$('#suppliertable').DataTable().row('#entity-' + entity['id']).remove();
			}
			$('#suppliertable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['charge-template'])
	<script type="text/javascript">
		function refreshTableWithCharge(charge, is_new) {
			let content = populateHtmlTemplateWithData($('#charge-template').html().toString(), entity);
			if (!is_new && $('#chargebacktable').DataTable().row('#charge-' + charge['id']).length) {
				$('#chargebacktable').DataTable().row('#charge-' + charge['id']).remove();
			}
			$('#chargebacktable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['warehouse-entry-template'])
	<script type="text/javascript">
		function refreshInboundOrderTable(data, is_new) {
			let content = populateHtmlTemplateWithData($('#warehouse-entry-template').html().toString(), data);
			if (!is_new && $('#inboundbookingtable').DataTable().row('#warehouse-' + data['id']).length) {
				$('#inboundbookingtable').DataTable().row('#warehouse-' + data['id']).remove();
			}
			if (data['is_open']) {
				$('#inboundbookingtable').DataTable().row.add($(content));
			}
			$('#inboundbookingtable').DataTable().draw();
		}
	</script>
@endif

@if ($controlSwitch['warehouse-entry-template'])
	<script type="text/javascript">
		function refreshOutboundOrderTable(data, is_new) {
			let content = populateHtmlTemplateWithData($('#warehouse-entry-template').html().toString(), data);
			if (!is_new && $('#pickinglisttable').DataTable().row('#warehouse-' + data['id']).length) {
				$('#pickinglisttable').DataTable().row('#warehouse-' + data['id']).remove();
			}
			if (data['is_open']) {
				$('#pickinglisttable').DataTable().row.add($(content));
			}
			$('#pickinglisttable').DataTable().draw();
		}
	</script>
@endif

@if ($controlSwitch['purchase-quote-modal'])
	<script type="text/javascript">
		function vuePurchaseQuoteDataSource() {
			// function that holds data
		}

		$(document).ready(function() {
			// display text of 'View PDF'
			vuePurchaseQuoteDataSource.button_pdf = "<i class=\"fa fa-btn fa-file-pdf-o\"></i>" + "{{ trans('forms.View PDF') }}";
			// display text of 'Create'
			vuePurchaseQuoteDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// display text of 'Update'
			vuePurchaseQuoteDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// display text of 'Approve'
			vuePurchaseQuoteDataSource.button_approve = "<i class=\"fa fa-btn fa-check-square-o\"></i>" + "{{ trans('forms.Approve') }}";
			// display text of 'Reject'
			vuePurchaseQuoteDataSource.button_reject = "<i class=\"fa fa-btn fa-thumbs-o-down\"></i>" + "{{ trans('forms.Disapprove') }}";
			// selection of entity
			vuePurchaseQuoteDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getSuppliersWithProduct('code', 'asc')->mapWithKeys(function ($item) { $fmtr = $item->currency->getFormat(true); return [ $item->id => [ 'display' => $item->code . '  (' . $item->name . ')', 'currency' => $item->currency_id, 'payment' => $item->payment_term_id, 'contact' => $item->contact->last()->id, 'regex' => $fmtr['regex'], 'symbol' => $fmtr['symbol'], 'fdigit' => $fmtr['fdigit'], 'min' => $fmtr['min'] ] ]; })->toArray()) !!};
			// selection of payment
			vuePurchaseQuoteDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of contact
			vuePurchaseQuoteDataSource.selection_contact = {!! json_encode(\App\User::getUsersIndexedByEntity(['supplier'])) !!};
			// selection of staff
			vuePurchaseQuoteDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of product
			vuePurchaseQuoteDataSource.selection_product = {!! json_encode(\App\UniqueTradable::getUniqueTradableIndexedBySupplierEntity()) !!};
			// selection of currency
			vuePurchaseQuoteDataSource.selection_currency = {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->get()->mapWithKeys(function ($item) { return [ $item->id => array_merge($item->getFormat(true), [ 'description' => $item->description ]) ]; })->toArray()) !!};
			// text of 'Create sales quote'
			vuePurchaseQuoteDataSource.text_create_purchase_quote = "{{ trans('vrm.New quote') }}";
			// text of 'View sales quote'
			vuePurchaseQuoteDataSource.text_view_purchase_quote = "{{ trans('vrm.View quote') }}";
			// text of 'Update sales quote'
			vuePurchaseQuoteDataSource.text_update_purchase_quote = "{{ trans('vrm.Update quote') }}";
			// text of 'Approve sales quote'
			vuePurchaseQuoteDataSource.text_approve_purchase_quote = "{{ trans('vrm.Approve quote') }}";
			// callback function when new order is submitted
			vuePurchaseQuoteDataSource.insertCallback = function(data) {
				refreshTableWithPurchaseQuote(data, true);
			};
			// callback function when new order is updated
			vuePurchaseQuoteDataSource.updateCallback = function(data) {
				refreshTableWithPurchaseQuote(data, false);
			}
		});
	</script>
@endif

@if ($controlSwitch['purchase-order-modal'])
	<script type="text/javascript">
		function vuePurchaseEntryDataSource() {
		  // function that holds data
		}

		$(document).ready(function() {
			// current user id
			vuePurchaseEntryDataSource.current_user_id = {{ auth()->user()->id }};
			// display text of 'View PDF'
			vuePurchaseEntryDataSource.button_pdf = "<i class=\"fa fa-btn fa-file-pdf-o\"></i>" + "{{ trans('forms.View PDF') }}";
			// display text of 'Create'
			vuePurchaseEntryDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// display text of 'Update'
			vuePurchaseEntryDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// display text of 'Approve'
			vuePurchaseEntryDataSource.button_approve = "<i class=\"fa fa-btn fa-check-square-o\"></i>" + "{{ trans('forms.Approve') }}";
			// display text of 'Reject'
			vuePurchaseEntryDataSource.button_reject = "<i class=\"fa fa-btn fa-thumbs-o-down\"></i>" + "{{ trans('forms.Disapprove') }}";
			// display text of 'Void'
			vuePurchaseEntryDataSource.button_void = "<i class=\"fa fa-btn fa-ban\"></i>" + "{{ trans('forms.Void') }}";
			// selection of entity
			vuePurchaseEntryDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getSuppliersWithProduct('code', 'asc')->mapWithKeys(function ($item) { $fmtr = $item->currency->getFormat(true); return [ $item->id => [ 'display' => $item->code . '  (' . $item->name . ')', 'currency' => $item->currency_id, 'payment' => $item->payment_term_id, 'regex' => $fmtr['regex'], 'symbol' => $fmtr['symbol'], 'fdigit' => $fmtr['fdigit'], 'min' => $fmtr['min'] ] ]; })->toArray()) !!};
			// selection of payment
			vuePurchaseEntryDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of contact
			vuePurchaseEntryDataSource.selection_contact = {!! json_encode(\App\User::getUsersIndexedByEntity(['supplier'])) !!};
			// selection of staff
			vuePurchaseEntryDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of product
			vuePurchaseEntryDataSource.selection_product = {!! json_encode(\App\UniqueTradable::getUniqueTradableIndexedBySupplierEntity()) !!};
			// selection of warehouse
			vuePurchaseEntryDataSource.selection_warehouse = {!! json_encode(\App\Location::getWarehouses('name', 'asc')->toArray()) !!};
			// selection of currency
			vuePurchaseEntryDataSource.selection_currency = {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of billing address
			vuePurchaseEntryDataSource.selection_billing = {!! json_encode(\App\Address::getAddressesIndexedByEntity(['supplier'], 'billing')) !!};
			// selection of shipping address
			vuePurchaseEntryDataSource.selection_shipping = {!! json_encode(\App\Address::getAddressesIndexedByEntity(['supplier'], 'shipping')) !!};
			// display text of 'View PDF'
			vuePurchaseEntryDataSource.text_new_entry = "{{ trans('vrm.New entry') }}";
			// text of today's date
			vuePurchaseEntryDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// text of 'Create purchase order'
			vuePurchaseEntryDataSource.text_create_purchase_order = "{{ trans('vrm.New order') }}";
			// text of 'Create purchase return'
			vuePurchaseEntryDataSource.text_create_purchase_return = "{{ trans('vrm.New return') }}";
			// text of 'View purchase order'
			vuePurchaseEntryDataSource.text_view_purchase_order = "{{ trans('vrm.View order') }}";
			// text of 'View purchase return'
			vuePurchaseEntryDataSource.text_view_purchase_return = "{{ trans('vrm.View return') }}";
			// text of 'Update purchase order'
			vuePurchaseEntryDataSource.text_update_purchase_order = "{{ trans('vrm.Update order') }}";
			// text of 'Update purchase return'
			vuePurchaseEntryDataSource.text_update_purchase_return = "{{ trans('vrm.Update return') }}";
			// text of 'Approve purchase order'
			vuePurchaseEntryDataSource.text_approve_purchase_order = "{{ trans('vrm.Approve order') }}";
			// text of 'Approve purchase return'
			vuePurchaseEntryDataSource.text_approve_purchase_return = "{{ trans('vrm.Approve return') }}";
			// callback function when new order is submitted
			vuePurchaseEntryDataSource.insertCallback = function(data) {
				refreshTableWithPurchaseEntry(data, true);
			};
			// callback function when new order is updated
			vuePurchaseEntryDataSource.updateCallback = function(data) {
				refreshTableWithPurchaseEntry(data, false);
			}
		});
	</script>
@endif

@if ($controlSwitch['warehouse-order-modal'])
	<script type="text/javascript">
		function vueWarehouseOrderDataSource() {
		  // function that holds data
		}

		$(document).ready(function() {
			// text for 'View order'
			vueWarehouseOrderDataSource.text_view_warehouse_order = "{{ trans('warehouse.View order') }}";
			// text for 'Process order'
			vueWarehouseOrderDataSource.text_process_warehouse_order = "{{ trans('warehouse.Process order') }}";
			// text for 'View PDF' button
			vueWarehouseOrderDataSource.button_pdf = "<i class=\"fa fa-btn fa-file-pdf-o\"></i>" + "{{ trans('forms.View PDF') }}";
			// text for 'Update' button
			vueWarehouseOrderDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// selection of shipping address
			vueWarehouseOrderDataSource.selection_shipping = {!! json_encode(\App\Address::getAddressesIndexedByEntity(['supplier','customer','employee','self'], 'shipping')) !!};
			// selection of staff
			vueWarehouseOrderDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of warehouse
			vueWarehouseOrderDataSource.selection_warehouse = {!! json_encode(\App\Location::getWarehouses('name', 'asc')->toArray()) !!};
			// selection of entity
			vueWarehouseOrderDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::orderBy('code', 'asc')->get()->mapWithKeys(function ($item) { $fmtr = $item->currency->getFormat(true); return [ $item->id => [ 'display' => $item->code . '  (' . $item->name . ')', 'currency' => $item->currency_id, 'payment' => $item->payment_term_id, 'regex' => $fmtr['regex'], 'symbol' => $fmtr['symbol'], 'fdigit' => $fmtr['fdigit'], 'min' => $fmtr['min'] ] ]; })->toArray()) !!};
			// selection of product
			vueWarehouseOrderDataSource.selection_product = {!! json_encode(\App\UniqueTradable::getProducts('sku', 'asc')->mapWithKeys(function ($item) { return [ $item->id => [ 'sku' => $item->sku, 'description' => $item->description ]]; })) !!};
			// callback function when order is updated
			vueWarehouseOrderDataSource.updateCallback = function(data) {
				switch (data['type']) {
					case 'receive':
						refreshInboundOrderTable(data, false);
						break;
					case 'deliver':
						refreshOutboundOrderTable(data, false);
						break;
					default:
						break;
				}
			};
		});
	</script>
@endif

@if ($controlSwitch['entity-modal'])
	<script type="text/javascript">
		function vueTaxableEntityDataSource() {
		  // function that holds data
		}

		$(document).ready(function() {
			// text for button 'create'
			vueTaxableEntityDataSource.button_create = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// text for button 'update'
			vueTaxableEntityDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// selection of country location
			vueTaxableEntityDataSource.selection_country = {!! json_encode(\App\Helpers\CountryHelper::getAllCountryOptions()) !!};
			// selection of payment term
			vueTaxableEntityDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->get()->mapWithKeys(function ($item) { return [ $item->id => [ 'symbol' => $item->symbol, 'description' => $item->description ]]; })->toArray()) !!};
			// selection of currency
			vueTaxableEntityDataSource.selection_currency =  {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->get()->mapWithKeys(function ($item) { return [$item->id => [ 'symbol' => $item->symbol, 'description' => $item->description ]]; })->toArray()) !!};
			// text of 'Create customer'
			vueTaxableEntityDataSource.text_create_supplier = "{{ trans('vrm.New supplier') }}";
			// text of 'View customer'
			vueTaxableEntityDataSource.text_view_supplier = "{{ trans('vrm.View supplier') }}";
			// text of 'Update customer'
			vueTaxableEntityDataSource.text_update_supplier = "{{ trans('vrm.Update supplier') }}";
			// callback function when new entity is entered
			vueTaxableEntityDataSource.insertCallback = function(data) {
				refreshTableWithEntity(data, true);
			};
			// callback function when existing entity is updated
			vueTaxableEntityDataSource.updateCallback = function(data) {
				refreshTableWithEntity(data, false);
			};
		});
	</script>
@endif

@if ($controlSwitch['charge-modal'])
	<script type="text/javascript">
		function vueChargeDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text of date of today
			vueChargeDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// default taxable entity id
			vueChargeDataSource.id_default_entity = {{ auth()->user()->entity->id }};
			// current user id
			vueChargeDataSource.id_current_user = {{ auth()->user()->id }};
			// text of 'browse file'
			vueChargeDataSource.text_browse_file = "{{ trans('tool.Browse file') }}";
			// text of 'attachment download failed'
			vueChargeDataSource.text_attachment_download_failed = "{{ trans('messages.Attachment download failed') }}";
			// text of 'upload file'
			vueChargeDataSource.text_upload_file = "{{ trans('tool.Upload file') }}";
			// text of 'view file'
			vueChargeDataSource.text_view_file = "{{ trans('tool.View file') }}";
			// text of 'new charge'
			vueChargeDataSource.text_new_charge = "{{ trans('finance.New charge') }}";
			// text of 'view charge'
			vueChargeDataSource.text_view_charge = "{{ trans('finance.View charge') }}";
			// text of 'update charge'
			vueChargeDataSource.text_update_charge = "{{ trans('finance.Update charge') }}";
			// text of 'submit charge'
			vueChargeDataSource.text_submit_charge = "{{ trans('finance.Submit charge') }}";
			// text of 'retract charge'
			vueChargeDataSource.text_retract_charge = "{{ trans('finance.Retract charge') }}";
			// text of 'approve charge'
			vueChargeDataSource.text_approve_charge = "{{ trans('finance.Approve charge') }}";
			// button of 'New charge'
			vueChargeDataSource.button_create = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// button of 'Update charge'
			vueChargeDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// button of 'Submit charge'
			vueChargeDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// button of 'Retract charge'
			vueChargeDataSource.button_retract = "<i class=\"fa fa-btn fa-times\"></i>" + "{{ trans('forms.Retract') }}";
			// button of 'Approve charge'
			vueChargeDataSource.button_approve = "<i class=\"fa fa-btn fa-check-square-o\"></i>" + "{{ trans('forms.Approve') }}";
			// button of 'disapprove charge'
			vueChargeDataSource.button_reject = "<i class=\"fa fa-btn fa-thumbs-o-down\"></i>" + "{{ trans('forms.Disapprove') }}";
			// selection of entity
			vueChargeDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getActiveSuppliers('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of staff
			vueChargeDataSource.selection_staff = {!! json_encode(\App\User::getActiveStaff('name', 'asc')->pluck('name', 'id')); !!};
			// selection of currency
			vueChargeDataSource.selection_currency = {!! json_encode(\App\Currency::getActiveCurrencies('symbol', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->symbol . '  (' . $item->description . ')' ]; })->toArray()); !!};
			// selection of expenditure item
			vueChargeDataSource.selection_item = {!! json_encode(\App\UniqueTradable::getActiveExpenditures('sku', 'asc')->pluck('sku', 'id')) !!};
			// callback function after update
			vueChargeDataSource.updateCallback = function (charge) {
				refreshTableWithCharge(charge, false);
			};
			// callback function after insert
			vueChargeDataSource.insertCallback = function (charge) {
				refreshTableWithCharge(charge, true);
			};
		});
	</script>
@endif

@if ($controlSwitch['supplier-stats-modal'])
	<script type="text/javascript">
		function vueSupplierStatsDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text
			vueSupplierStatsDataSource.text_runrate = "{{ trans('finance.Runrate') }}";
			vueSupplierStatsDataSource.text_month = "{{ trans('tool.month') }}";
			vueSupplierStatsDataSource.text_volume = "{{ trans('finance.Volume') }}";
			vueSupplierStatsDataSource.text_chart_error = "{{ trans('crm.Performance statistics cannot be generated') }}";
		});
	</script>
@endif

@if ($controlSwitch['purchase-quote-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/purchase_quote.js') }}"></script>
@endif

@if ($controlSwitch['purchase-order-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/purchase_order.js') }}"></script>
@endif

@if ($controlSwitch['warehouse-order-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/pregenerated_warehouse_order.js') }}"></script>
@endif

@if ($controlSwitch['entity-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/taxable_entity.js') }}"></script>
@endif

@if ($controlSwitch['warehouse-entry-template'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/warehouse_transaction.js') }}"></script>
@endif

@if ($controlSwitch['charge-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/charge_entry.js') }}"></script>
@endif

@if ($controlSwitch['supplier-stats-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/supplier_stats.js') }}"></script>
@endif

@endsection
