@extends('layouts.app')

@section('additional-style')
	<link rel="stylesheet" type="text/css" href="/external/imagebox/css/style.css">
@endsection

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<!-- charge entry modal -->
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.charge_entry'))

			<div id="wipexpwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Pending expense') }}</h4></td>
							<td align='right'>
								<button type="button" class="btn btn-primary" onclick="createChargeEntryInModal()" value="{{ trans('finance.New expense') }}">{{ trans('finance.New expense') }}
								</button>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="wipexptable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Expense') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Item') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Expense') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Item') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax -->
							<tr>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div id="apprexpwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Approval required') }}</h4></td>
							<td align='right'>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="apprexptable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Expense') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Item') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Expense') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Item') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax -->
							<tr>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
</div>

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
	<li style="text-align:center;"><b>{{ trans('messages.Quick scroll menu') }}</b></li>
	<li class="divider"></li>
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#wipexpwindow').offset().top}, 500);">{{ trans('finance.Pending expense') }}</a></li>
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#apprexpwindow').offset().top}, 500);">{{ trans('finance.Approval required') }}</a></li>
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('.container').offset().top}, 500);">{{ trans('messages.Return to top') }}<i style="padding-left:1em;" class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
</ul>
@endsection

@section('post-content')
	<script type="text/javascript" src="{{ asset('js/DataTableHelper.js') }}" ></script>

	<script type="text/javascript" src="{{ asset('js/HtmlTemplateHelper.js') }}" ></script>

	<script src="{{ asset('external/imagebox/js/jquery.imagemodal.js') }}"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			$('#wipexptable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/expense/dashboard/in-progress', { }, '#wipexptable', '#wip-exp-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\ExpenseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 1, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#wipexptable');
			});
		} );
		$(document).ready(function() {
			$('#apprexptable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/expense/dashboard/need-approval', { }, '#apprexptable', '#appr-exp-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\ExpenseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 1, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 6 }, { visible : false, targets : 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#apprexptable');
			});
		} );
	</script>

	<script type="text/javascript" src="{{ asset('js/ContextMenu.js') }}"></script>

	<script type="text/javascript">

		$(".container").contextMenu({
			menuSelector: "#contextMenu",
			/*
			menuSelected: function (invokedOn, selectedMenu) {
				var msg = "You selected the menu item '" + selectedMenu.text() + "' on the value '" + invokedOn.text() + "'";
				alert(msg);
			}
			*/
		});
	</script>

	<script id="wip-exp-template" type="text/x-custom-template">
		<tr id="expense-{id}">
			<td id="title-cell">{title}</td>
			<td id="incur-date-cell" data-order="{incur_date}">{incur_date_display}</td>
			<td id="item-count-cell">{items}</td>
			<td id="total-cell" class="text-right">{total}</td>
			<td id="status-cell">{status}</td>
			<td id="search-key-cell">{search-key}</td>
			<td id="button-cell">
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewChargeEntryInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Update') }}" onclick="updateChargeEntryInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
				<button data-condition="{can_submit}" class='btn btn-info btn-xs' title="{{ trans('forms.Submit') }}" onclick="submitChargeEntryInModal({id})"><i class="fa fa-file-text" aria-hidden="true"></i></button>
				<button data-condition="{can_retract}" class='btn btn-info btn-xs' title="{{ trans('forms.Retract') }}" onclick="retractChargeEntryInModal({id})"><i class="fa fa-times" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>

	<script id="appr-exp-template" type="text/x-custom-template">
		<tr id="expense-{id}">
			<td id="title-cell">{title}</td>
			<td id="incur-date-cell" data-order="{incur_date}">{incur_date_display}</td>
			<td id="item-count-cell">{items}</td>
			<td id="total-cell" class="text-right">{total}</td>
			<td id="status-cell">{status}</td>
			<td id="search-key-cell">{search-key}</td>
			<td id="button-cell">
				<button data-condition="{can_approve}" class='btn btn-info btn-xs' title="{{ trans('forms.Approve') }}" onclick="approveChargeEntryInModal({id})"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>

	<script type="text/javascript">

		function vueChargeDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text of date of today
			vueChargeDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// default taxable entity id
			vueChargeDataSource.id_default_entity = {{ auth()->user()->entity->id }};
			// current user id
			vueChargeDataSource.id_current_user = {{ auth()->user()->id }};
			// text of 'browse file'
			vueChargeDataSource.text_browse_file = "{{ trans('tool.Browse file') }}";
			// text of 'attachment download failed'
			vueChargeDataSource.text_attachment_download_failed = "{{ trans('messages.Attachment download failed') }}";
			// text of 'upload file'
			vueChargeDataSource.text_upload_file = "{{ trans('tool.Upload file') }}";
			// text of 'view file'
			vueChargeDataSource.text_view_file = "{{ trans('tool.View file') }}";
			// text of 'new charge'
			vueChargeDataSource.text_new_charge = "{{ trans('finance.New charge') }}";
			// text of 'view charge'
			vueChargeDataSource.text_view_charge = "{{ trans('finance.View charge') }}";
			// text of 'update charge'
			vueChargeDataSource.text_update_charge = "{{ trans('finance.Update charge') }}";
			// text of 'submit charge'
			vueChargeDataSource.text_submit_charge = "{{ trans('finance.Submit charge') }}";
			// text of 'retract charge'
			vueChargeDataSource.text_retract_charge = "{{ trans('finance.Retract charge') }}";
			// text of 'approve charge'
			vueChargeDataSource.text_approve_charge = "{{ trans('finance.Approve charge') }}";
			// button of 'New charge'
			vueChargeDataSource.button_create = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// button of 'Update charge'
			vueChargeDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// button of 'Submit charge'
			vueChargeDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// button of 'Retract charge'
			vueChargeDataSource.button_retract = "<i class=\"fa fa-btn fa-times\"></i>" + "{{ trans('forms.Retract') }}";
			// button of 'Approve charge'
			vueChargeDataSource.button_approve = "<i class=\"fa fa-btn fa-check-square-o\"></i>" + "{{ trans('forms.Approve') }}";
			// button of 'disapprove charge'
			vueChargeDataSource.button_reject = "<i class=\"fa fa-btn fa-thumbs-o-down\"></i>" + "{{ trans('forms.Disapprove') }}";
			// selection of entity
			vueChargeDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getActiveEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of staff
			vueChargeDataSource.selection_staff = {!! json_encode(\App\User::getActiveStaff('name', 'asc')->pluck('name', 'id')); !!};
			// selection of currency
			vueChargeDataSource.selection_currency = {!! json_encode(\App\Currency::getActiveCurrencies('symbol', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->symbol . '  (' . $item->description . ')' ]; })->toArray()); !!};
			// selection of expenditure item
			vueChargeDataSource.selection_item = {!! json_encode(\App\UniqueTradable::getActiveExpenditures('sku', 'asc')->pluck('sku', 'id')) !!};
			// callback function after update
			vueChargeDataSource.updateCallback = function (expense) {
					// update 'wipexptable' table.
					// can't dynamically change datatable content, so we remove and re-insert.
					if ($('#wipexptable').DataTable().row('#expense-' + expense['id']).length) {
						$('#wipexptable').DataTable().row('#expense-' + expense['id']).remove();
						$('#wipexptable').DataTable().row.add($(populateHtmlTemplateWithData($('#wip-exp-template').html().toString(), expense))).draw();
					}
					// update 'apprexptable' table
					if ($('#apprexptable').DataTable().row('#expense-' + expense['id']).length) {
						$('#apprexptable').DataTable().row('#expense-' + expense['id']).remove();
						$('#apprexptable').DataTable().row.add($(populateHtmlTemplateWithData($('#appr-exp-template').html().toString(), expense))).draw();
					}
				};
			// callback function after insert
			vueChargeDataSource.insertCallback = function (expense) {
					$('#wipexptable').DataTable().row.add($(populateHtmlTemplateWithData($('#wip-exp-template').html().toString(), expense))).draw();
					if (expense['can_approve']) {
						$('#apprexptable').DataTable().row.add($(populateHtmlTemplateWithData($('#appr-exp-template').html().toString(), expense))).draw();
					}
				};
		});
	</script>

	<script type="text/javascript" src="{{ asset('js/embedded_modal/charge_entry.js') }}"></script>

@endsection
