@extends('layouts.app')

@section('additional-style')
	<link rel="stylesheet" type="text/css" href="/external/imagebox/css/style.css">

	<link rel="stylesheet" type="text/css" href="/external/chat-bubble/chat-bubble.css">

@if (!App::environment('local'))
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/min/dropzone.min.css">
@else
	<link rel="stylesheet" href="{{ asset('external/dropzone/5.7.0/dropzone.min.css') }}">
@endif
@endsection

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">

			<!-- modal to create new request -->
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.new_interaction_form'))

			<!-- interaction modal -->
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.interaction_form'))

			<div class="panel panel-default">
				<div class="panel-heading">
					<button type="button" class="btn btn-primary pull-right" onclick="openNewInteractionModal();">{{ trans('forms.New request') }}</button>
          <h4>{{ trans('messages.Interaction') }}</h4>
        </div>

				<div class="panel-body">
					<table id="interactiontable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Summary') }}</th>
								<th>{{ trans('forms.Initiate date') }}</th>
								<th>{{ trans('forms.Update date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Description') }}</th>
								<th>{{ trans('forms.Initiate date') }}</th>
								<th>{{ trans('forms.Update date') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax -->
							<tr>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('post-content')

	<script src="{{ asset('external/imagebox/js/jquery.imagemodal.js') }}"></script>

	<script type="text/javascript" src="{{ asset('js/DataTableHelper.js') }}" ></script>

	<script type="text/javascript" src="{{ asset('js/HtmlTemplateHelper.js') }}" ></script>

@if (!App::environment('local'))
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/min/dropzone.min.js"></script>
@else
	<script type="text/javascript" src="{{ asset('external/dropzone/5.7.0/dropzone.min.js') }}"></script>
@endif

	<script id="interaction-table-template" type="text/x-custom-template">
		<tr id="interaction-{id}">
			<td>
				<p style="padding-right:2em;display:inline;">{description}</p>
				<i data-condition="'{type}' == 'request'" class="fa fa-commenting-o" aria-hidden="true" title="{{ trans('forms.Request') }}"></i>
				<i data-condition="'{type}' == 'assignment'" class="fa fa-check-square-o" aria-hidden="true" title="{{ trans('forms.Assignment') }}"></i>
				<i data-condition="'{status}' == 'requested'" class="fa fa-comments-o" aria-hidden="true" title="{{ trans('status.Requested') }}"></i>
				<i data-condition="'{status}' == 'evaluating'" class="fa fa-balance-scale" aria-hidden="true" title="{{ trans('status.Evaluating') }}"></i>
				<i data-condition="'{status}' == 'in-progress'" class="fa fa-cogs" aria-hidden="true" title="{{ trans('status.In-progress') }}"></i>
				<i data-condition="'{status}' == 'closed'" class="fa fa-archive" aria-hidden="true" title="{{ trans('status.Closed') }}"></i>
			</td>
			<td class="text-right" data-order="{create_date}">{create_date_display}</td>
			<td class="text-right" data-order="{update_date}">{update_date_display}</td>
			<td>{search-key}</td>
			<td>
				<button class='btn btn-info btn-xs' title="{{ trans('forms.View') . "/" . trans('forms.Edit') }}" onclick="accessInteractionInModal({id})"><i class="fa fa-pencil" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>

	<script type="text/javascript">

		$(document).ready(function() {
			$('#interactiontable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/interaction/ajax', { }, '#interactiontable', '#interaction-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\Interaction::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 1, 'desc' ]],
					columnDefs : [{ orderable : false, targets : 4 }, { visible : false, targets : 3 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#interactiontable');
			});
		} );

		$(document).ready(function() {

		  Dropzone.options.uploadedFiles = {
		    init : function () {
		      this.on("addedfile", function (data) {
		        let ext = data.name.split('.').pop().toLowerCase();

		        switch (ext) {
		        case "pdf":
		          $(data.previewElement).find(".dz-image img").attr("src", "/images/pdf-icon.png");
		          break;
		        case "gif":
		        case "jpg":
		        case "jpeg":
		        case "png":
		          $(data.previewElement).find(".dz-image img").attr("src", "/images/image-icon.png");
		          break;
		        case "mp4":
		          $(data.previewElement).find(".dz-image img").attr("src", "/images/video-icon.png");
		          break;
		        }
		      });
		      this.on("success", function (data, response) {
		        let newIds = response['ids'];
						let oldIdStringSource = $('#embeddedInteractionModal #newLogModal').hasClass('in')
									? '#embeddedInteractionModal #newLogModal'
									: ($('#embeddedNewInteractionModal').hasClass('in') ? '#embeddedNewInteractionModal' : null);
		        let oldIdString = $(oldIdStringSource + ' div.modal-body input#files').val();
		        let oldIds = (oldIdString.length > 0) ? oldIdString.split(",") : [];
		        // if uploading multiple files, ids will duplicate, duplicates are
		        // eliminated by constructing unique set and then covert back to array
		        let newIdString = Array.from(new Set(oldIds.concat(newIds)));
		        $(oldIdStringSource + ' div.modal-body input#files').val(newIdString.join(","));
		      });
		    },
		    uploadMultiple : true,
		    url : "/interaction/upload",
		    thumbnailWidth : 80,
		    thumbnailHeight: 80,
		    sending: function(file, xhr, formData) {
		      formData.append("_token", vueInteractionModal.modal.csrf);
		    },
		  }
		});

		function vueInteractionDataSource() {
			// function that holds data
		}

		$(document).ready(function() {
			vueInteractionDataSource.text_download_failed = '{{ trans('messages.Attachment download failed') }}';
			vueInteractionDataSource.text_validation_required = '{{ trans('validation.required') }}';
			vueInteractionDataSource.selection_status = {
					requested : {
						display : '{{ trans('status.Requested') }}',
						class : [ 'request' ],
					},
					evaluating : {
						display : '{{ trans('status.Evaluating') }}',
						class : [ 'request' ],
					},
					'in-progress' : {
						display : '{{ trans('status.In-progress') }}',
						class : [ 'assignment' ],
					},
					closed : {
						display : '{{ trans('status.Closed') }}',
						class : [ 'request', 'assignment' ],
					}
				};
			vueInteractionDataSource.selection_type = {
					request : '{{ trans('forms.Request') }}',
					assignment : '{{ trans('forms.Assignment') }}',
				};
			vueInteractionDataSource.insertCallback = function (interaction) {
					$('#interactiontable').DataTable().row.add($(populateHtmlTemplateWithData($('#interaction-table-template').html().toString(), interaction))).draw();
				};
			vueInteractionDataSource.updateCallback = function (interaction) {
					if ($('#interactiontable').DataTable().row('#interaction-' + interaction['id']).length) {
						$('#interactiontable').DataTable().row('#interaction-' + interaction['id']).remove();
						$('#interactiontable').DataTable().row.add($(populateHtmlTemplateWithData($('#interaction-table-template').html().toString(), interaction))).draw();
					}
				};
		});

	</script>

	<script type="text/javascript" src="{{ asset('js/embedded_modal/new_interaction_form.js') }}"></script>

	<script type="text/javascript" src="{{ asset('js/embedded_modal/interaction_form.js') }}"></script>

@endsection
