@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<!-- purchase-process form modal -->
		@if ($controlSwitch['purchase-process-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.purchase_process'))
		@endif

			<!-- sales-process form modal -->
		@if ($controlSwitch['sales-process-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.sales_process'))
		@endif

			<!-- transactable form modal -->
		@if ($controlSwitch['transactable-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.transactable_form'))
		@endif

			<!-- taxable-entity form modal -->
		@if ($controlSwitch['taxable-entity-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.taxable_entity'))
		@endif

			<!-- tradable-transaction modal -->
		@if ($controlSwitch['tradable-transaction-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.tradable_transaction'))
		@endif

			<!-- taccount-transaction modal -->
		@if ($controlSwitch['taccount-transaction-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.taccount_transaction'))
		@endif

			<!-- charge-entry modal -->
		@if ($controlSwitch['charge-entry-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.charge_entry'))
		@endif

			<!-- taccount-form modal -->
		@if ($controlSwitch['taccount-form-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.taccount_form'))
		@endif

			<!-- income-receipt modal -->
		@if ($controlSwitch['income-receipt-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.income_form'))
		@endif

			<!-- payment-disbursement modal -->
		@if ($controlSwitch['payment-disbursement-modal'])
			@include(prioritizeCustomizedTemplateOverDefault('embedded_modal.payment_form'))
		@endif


		@if ($controlSwitch['receivable-window'])
			<div id="receivablewindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Receivable') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['sales-process-modal'])
								<input type="button" class="btn btn-primary" onclick="getProcessableOrder('sales', 'processable-salesorder-template', 'receivableModal')" value="{{ trans('finance.New receivable') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="receivabletable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Document') }}</th>
								<th>{{ trans('finance.Customer') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Due date') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Balance') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Document') }}</th>
								<th>{{ trans('finance.Customer') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Due date') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Balance') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need an initial stuff row  in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['customer-window'])
			<div id="customerwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Customer') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-customer-button'])
								<input type="button" class="btn btn-primary" onclick="createTaxableEntityInModal('customer')" value="{{ trans('finance.New customer') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="customertable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Name') }}</th>
								<th>{{ trans('finance.Code') }}</th>
								<th>{{ trans('finance.Contact') }}</th>
								<th>{{ trans('finance.Region') }}</th>
								<th>{{ trans('finance.Outstanding transactable') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Name') }}</th>
								<th>{{ trans('finance.Code') }}</th>
								<th>{{ trans('finance.Contact') }}</th>
								<th>{{ trans('finance.Region') }}</th>
								<th>{{ trans('finance.Outstanding transactable') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need an initial stuffer row  in order to get 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['payable-window'])
			<div id="payablewindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Payable') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['purchase-process-modal'])
								<input type="button" class="btn btn-primary" data-toggle="modal" data-target="#payableModal" value="{{ trans('finance.New payable') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="payabletable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Document') }}</th>
								<th>{{ trans('finance.Customer') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Due date') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Balance') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Document') }}</th>
								<th>{{ trans('finance.Customer') }}</th>
								<th>{{ trans('finance.Incur date') }}</th>
								<th>{{ trans('finance.Due date') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Balance') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need an initial stuffer row  in order to get 'data-order' attribute active -->
							<tr>
								<td data-order="000000"></td>
								<td></td>
								<td data-order="1970-01-01"></td>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['supplier-window'])
			<div id="supplierwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Supplier') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-supplier-button'])
								<input type="button" class="btn btn-primary" onclick="createTaxableEntityInModal('supplier')" value="{{ trans('finance.New supplier') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="suppliertable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Name') }}</th>
								<th>{{ trans('finance.Code') }}</th>
								<th>{{ trans('finance.Contact') }}</th>
								<th>{{ trans('finance.Region') }}</th>
								<th>{{ trans('finance.Outstanding transactable') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Name') }}</th>
								<th>{{ trans('finance.Code') }}</th>
								<th>{{ trans('finance.Contact') }}</th>
								<th>{{ trans('finance.Region') }}</th>
								<th>{{ trans('finance.Outstanding transactable') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need an initial stuffer row  in order to get 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['expense-window'])
			<div id="chargewindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('finance.Charge') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-expense-button'])
								<input type="button" class="btn btn-primary" onclick="createChargeEntryInModal()" value="{{ trans('finance.New charge') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="chargetable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Date') }}</th>
								<th>{{ trans('finance.Title') }}</th>
								<th>{{ trans('finance.Entity') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Date') }}</th>
								<th>{{ trans('finance.Title') }}</th>
								<th>{{ trans('finance.Entity') }}</th>
								<th>{{ trans('finance.Total') }}</th>
								<th>{{ trans('finance.Status') }}</th>
								<th></th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax -->
							<tr>
								<td data-order="1970-01-01"></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['inventory-window'])
			<div id="inventorywindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('warehouse.Inventory') }}</h4></td>
							<td align='right'>
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="inventorytable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Owner') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('forms.Location') }}</th>
								<th>{{ trans('forms.SKU') }}</th>
								<th>{{ trans('forms.Owner') }}</th>
								<th>{{ trans('forms.Balance') }}</th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['taccount-window'])
			<div id="acctwindow" class="panel panel-default">
				<div class="panel-heading">
					<table width='100%'>
						<tr>
							<td><h4>{{ trans('accounting.Chart account') }}</h4></td>
							<td align='right'>
							@if ($controlSwitch['create-account-button'])
								<input type="button" class="btn btn-primary" onclick="createTaccountFormInModal()" value="{{ trans('accounting.New chart account') }}"/>
							@endif
							</td>
						</tr>
					</table>
				</div>

				<div class="panel-body">
					<table id="accttable" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ trans('finance.Account') }}</th>
								<th>{{ trans('finance.Type') }}</th>
								<th>{{ trans('finance.Currency') }}</th>
								<th>{{ trans('finance.Description') }}</th>
								<th></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>{{ trans('finance.Account') }}</th>
								<th>{{ trans('finance.Type') }}</th>
								<th>{{ trans('finance.Currency') }}</th>
								<th>{{ trans('finance.Description') }}</th>
								<th></th>
							</tr>
						</tfoot>
						<tbody>
							<!-- body generated by ajax; need an initial stuffer row  in order to get 'data-order' attribute active -->
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		@endif

		@if ($controlSwitch['report-window'])
			<div id="reportwindow" class="panel panel-default">
				<div class="panel-heading"><h4>{{ trans('messages.Report') }}</h4></div>

				<div class="panel-body">
				@if ($controlSwitch['inventory-report'])
					<a href="{{ url('accounting/inventory/print?date=' . \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d"))) }}" class="btn btn-sq-lg btn-info" ><span class="fa fa-2x fa-file-text-o"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Inventory report")) !!}</a>
					<a class="btn btn-sq-lg btn-info" href="{{ url('accounting/aging') }}"><span class="fa fa-2x fa-file-text-o"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.Aging inventory")) !!}</a>
					<a class="btn btn-sq-lg btn-info" disabled><span class="fa fa-2x fa-question-circle"></span><br/>{!! str_replace(" ", "<br/>", trans("warehouse.In-transit inventory")) !!}</a>
				@endif
				</div>
			</div>
		@endif

		@if ($controlSwitch['tool-window'])
			<div id="toolwindow" class="panel panel-default">
				<div class="panel-heading"><h4>{{ trans('messages.Tool') }}</h4></div>

				<div class="panel-body">
				@if ($controlSwitch['adjust-inventory-button'])
					<a class="btn btn-sq-lg btn-info" href="{{ url('finance/adjust-inventory') }}"><span class="fa fa-2x fa-cube"></span><br/>{!! str_replace(" ", "<br/>", trans("accounting.Adjust inventory")) !!}</a>
				@endif
				@if ($controlSwitch['adjust-consignment-button'])
					<a class="btn btn-sq-lg btn-info" href="{{ url('accounting/adjust-consignment') }}"><span class="fa fa-2x fa-cube"></span><br/>{!! str_replace(" ", "<br/>", trans("accounting.Adjust consignment")) !!}</a>
				@endif
				@if ($controlSwitch['create-expense-button'])
					<a class="btn btn-sq-lg btn-info" href="{{ url('commission/wizard') }}"><span class="fa fa-2x fa-dollar"></span><br/>{!! str_replace(" ", "<br/>", trans("forms.Calculate commission")) !!}</a>
				@endif
				@if ($controlSwitch['adjust-cogs-button'])
					<a class="btn btn-sq-lg btn-info" disabled><span class="fa fa-2x fa-usd"></span><br/>{!! str_replace(" ", "<br/>", trans("accounting.Adjust COGS")) !!}</a>
				@endif
				</div>
			</div>
		@endif

		</div>
	</div>
</div>

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
	<li style="text-align:center;"><b>{{ trans('messages.Quick scroll menu') }}</b></li>
	<li class="divider"></li>
@if ($controlSwitch['receivable-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#receivablewindow').offset().top}, 500);">{{ trans('finance.Receivable') }}</a></li>
@endif
@if ($controlSwitch['customer-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#customerwindow').offset().top}, 500);">{{ trans('finance.Customer') }}</a></li>
@endif
@if ($controlSwitch['payable-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#payablewindow').offset().top}, 500);">{{ trans('finance.Payable') }}</a></li>
@endif
@if ($controlSwitch['supplier-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#supplierwindow').offset().top}, 500);">{{ trans('finance.Supplier') }}</a></li>
@endif
@if ($controlSwitch['expense-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#chargewindow').offset().top}, 500);">{{ trans('finance.Charge') }}</a></li>
@endif
@if ($controlSwitch['inventory-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#inventorywindow').offset().top}, 500);">{{ trans('warehouse.Inventory') }}</a></li>
@endif
@if ($controlSwitch['taccount-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#acctwindow').offset().top}, 500);">{{ trans('accounting.Chart account') }}</a></li>
@endif
@if ($controlSwitch['report-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#reportwindow').offset().top}, 500);">{{ trans('messages.Report') }}</a></li>
@endif
@if ($controlSwitch['tool-window'])
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('#toolwindow').offset().top}, 500);">{{ trans('messages.Tool') }}</a></li>
@endif
	<li><a tabindex="-1" onclick="$('html,body').animate({scrollTop:$('.container').offset().top}, 500);">{{ trans('messages.Return to top') }}<i style="padding-left:1em;" class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
</ul>
@endsection

@section('post-content')

	<script type="text/javascript" src="{{ asset('js/ContextMenu.js') }}"></script>

	<script type="text/javascript">

		$(".container").contextMenu({
			menuSelector: "#contextMenu",
			/*
			menuSelected: function (invokedOn, selectedMenu) {
				var msg = "You selected the menu item '" + selectedMenu.text() + "' on the value '" + invokedOn.text() + "'";
				alert(msg);
			}
			*/
		});
	</script>

	<script type="text/javascript" src="{{ asset('js/DataTableHelper.js') }}" ></script>

	<script type="text/javascript" src="{{ asset('js/HtmlTemplateHelper.js') }}" ></script>

	<script src="{{ asset('external/imagebox/js/jquery.imagemodal.js') }}"></script>

@if ($controlSwitch['sales-process-modal'])
	<script id="processable-salesorder-template" type="text/x-custom-template">
		<li>
			<span data-condition="'{type}' == 'order'">
				<a onclick="$('#receivableModal').modal('hide'); processSalesProcessInModal({id});">#{increment}</a>
				<span style="padding-left:30px;">{customer}</span>
				<span style="padding-left:20px;">{balance}</span>
			</span>
			<span data-condition="'{type}' != 'order'">
				<a onclick="$('#receivableModal').modal('hide'); processSalesProcessInModal({id});">#R{increment}</a>
				<span style="padding-left:30px;">{customer}</span>
				<span style="padding-left:20px;">{balance}</span>
			</span>
		</li>
	</script>
@endif

@if ($controlSwitch['purchase-process-modal'])
	<script id="processable-purchaseorder-template" type="text/x-custom-template">
		<li>
			<span data-condition="'{type}' == 'order'">
				<a onclick="$('#payableModal').modal('hide'); processPurchaseProcessInModal({id});">#{title}</a>
				<span style="padding-left:30px;">{supplier}</span>
				<span style="padding-left:20px;">{balance}</span>
			</span>
			<span data-condition="'{type}' != 'order'">
				<a onclick="$('#receivableModal').modal('hide'); processPurchaseProcessInModal({id});">#R{title}</a>
				<span style="padding-left:30px;">{supplier}</span>
				<span style="padding-left:20px;">{balance}</span>
			</span>
		</li>
	</script>
@endif

@if ($controlSwitch['entity-template'])
	<script id="entity-table-template" type="text/x-custom-template">
		<tr id="entity-{id}">
			<td>
				<p style="padding-right:2em;display:inline;">{name}</p>
				<i data-condition="{is_active}" class="fa fa-heartbeat" aria-hidden="true" title="{{ trans('status.Active') }}"></i>
			</td>
			<td>{code}</td>
			<td>{contact}</td>
			<td>{region}</td>
			<td class="text-right">{outstanding_transactable}</td>
			<td>{search-key}</td>
			<td style="width:110px">
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewTaxableEntityInModal({id})">
					<i class="fa fa-eye" aria-hidden="true"></i>
				</button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updateTaxableEntityInModal({id})">
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
				</button>
				<button data-condition="{can_view} &amp;&amp; ('{type}' == 'customer')" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="window.location.href='/crm/viewcustomer/{id}'">
					<i class="fa fa-line-chart" aria-hidden="true"></i>
				</button>
				<button data-condition="{can_view} &amp;&amp; ('{type}' == 'supplier')" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="window.location.href='/vrm/viewsupplier/{id}'">
					<i class="fa fa-line-chart" aria-hidden="true"></i>
				</button>
				<button data-condition="{can_transact} &amp;&amp; ('{type}' == 'customer')" class='btn btn-info btn-xs' title="{{ trans('forms.Receive payment') }}" onclick="payReceivableInModal({id})">
					<i style="padding-left:3px;padding-right:3px;" class="fa fa-usd" aria-hidden="true"></i>
				</button>
				<button data-condition="{can_transact} &amp;&amp; ('{type}' == 'supplier')" class='btn btn-info btn-xs' title="{{ trans('forms.Issue payment') }}" onclick="payPayableInModal({id})">
					<i style="padding-left:3px;padding-right:3px;" class="fa fa-usd" aria-hidden="true"></i>
				</button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['transactable-template'])
	<script id="transactable-table-template" type="text/x-custom-template">
		<tr id="transactable-{id}">
			<td data-order="{title_numeral}"><p style="padding-right:2em;display:inline;">{title}</p>
				<i data-condition="{is_closed}" class="fa fa-times" aria-hidden="true" title="{{ trans('status.Closed') }}"></i>
				<i data-condition="{is_void}" class="fa fa-ban" aria-hidden="true" title="{{ trans('status.Void') }}"></i>
			</td>
			<td>{entity}</td>
			<td data-order="{incur_date}">{incur_date_display}</td>
			<td data-condition="{is_pastdue}" data-order="{due_date}" class="text-danger">{due_date_display}</td>
			<td data-condition="!{is_pastdue}" data-order="{due_date}" >{due_date_display}</td>
			<td class="text-right">{total}</td>
			<td data-condition="{is_pastdue}" class="text-right text-danger">{balance}</td>
			<td data-condition="!{is_pastdue}" class="text-right">{balance}</td>
			<td>{search-key}</td>
			<td style="width:55px">
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewTransactableEntryInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_void}" class='btn btn-info btn-xs' title="{{ trans('forms.Void') }}" onclick="voidTransactableEntryInModal({id})"><i class="fa fa-ban" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['expense-template'])
	<script id="expense-table-template" type="text/x-custom-template">
		<tr id="charge-{id}">
			<td data-order="{incur_date}"><p style="padding-right:2em;display:inline;">{incur_date_display}</p>
				<i data-condition="{is_valid}" class="fa fa-check-circle" aria-hidden="true" title="{{ trans('status.Valid') }}"></i>
				<i data-condition="{is_approved}" class="fa fa-check-square-o" aria-hidden="true" title="{{ trans('status.Approved') }}"></i>
			</td>
			<td>{title}</td>
			<td>{entity}</td>
			<td class="text-right">{total}</td>
			<td>{status}</td>
			<td>{search-key}</td>
			<td style="width:82px">
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewChargeEntryInModal({id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_submit}" class='btn btn-info btn-xs' title="{{ trans('forms.Submit') }}" onclick="submitChargeEntryInModal({id})"><i class="fa fa-file-text" aria-hidden="true"></i></button>
				<button data-condition="{can_retract}" class='btn btn-info btn-xs' title="{{ trans('forms.Retract') }}" onclick="retractChargeEntryInModal({id})"><i class="fa fa-times" aria-hidden="true"></i></button>
				<button data-condition="{can_approve}" class='btn btn-info btn-xs' title="{{ trans('forms.Approve') }}" onclick="approveChargeEntryInModal({id})"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['inventory-entry-template'])
	<script id="inventory-entry-template" type="text/x-custom-template">
		<tr id="tradable-{location_id}-{entity_id}-{sku_id}">
			<td>{location}</td>
			<td>{sku}</td>
			<td>{entity}</td>
			<td class="text-right">{balance}</td>
			<td  style="width:28px" data-condition="{can_view}">
				<button class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewTradableTransactionsInModal({location_id}, {entity_id}, {sku_id})"><i class="fa fa-eye" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['taccount-template'])
	<script id="taccount-entry-template" type="text/x-custom-template">
		<tr id="taccount-{id}">
			<td>
				<p style="padding-right:2em;display:inline;">{account}</p>
				<i data-condition="active" class="fa fa-heartbeat" aria-hidden="true" title="{{ trans('status.Active') }}"></i>
			</td>
			<td>{type}</td>
			<td>{currency}</td>
			<td>{description}</td>
			<td style="width:55px">
				<button data-condition="{can_view}" class='btn btn-info btn-xs' title="{{ trans('forms.View') }}" onclick="viewTaccountTransactionInModal({id}, '{description}', '{currency}')"><i class="fa fa-eye" aria-hidden="true"></i></button>
				<button data-condition="{can_edit}" class='btn btn-info btn-xs' title="{{ trans('forms.Edit') }}" onclick="updateTaccountFormInModal({id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
			</td>
		</tr>
	</script>
@endif

@if ($controlSwitch['receivable-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#receivabletable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/transactable/receivable/ajax', { }, '#receivabletable', '#transactable-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\TransactableHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 2, 'desc' ]],
					columnDefs : [{ orderable: false, targets: 7 }, { "visible": false, targets: 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#receivabletable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['customer-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#customertable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/entity/customer/ajax', { }, '#customertable', '#entity-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\TaxableEntity::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable: false, targets: 6 }, { "visible": false, targets: 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#customertable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['payable-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#payabletable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/transactable/payable/ajax', { }, '#payabletable', '#transactable-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\TransactableHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 2, 'desc' ]],
					columnDefs : [{ orderable: false, targets: 7 }, { "visible": false, targets: 6 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#payabletable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['supplier-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#suppliertable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/entity/supplier/ajax', { }, '#suppliertable', '#entity-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\TaxableEntity::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable: false, targets: 6 }, { "visible": false, targets: 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#suppliertable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['expense-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#chargetable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/expense/all/ajax', { }, '#chargetable', '#expense-table-template', '{{ trans('tool.Enter search keyword') }}', '{{ \App\ExpenseHeader::generateSearchTips("\\n") }}', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'desc' ]],
					columnDefs : [{ orderable: false, targets: 6 },{ "visible": false, targets: 5 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#chargetable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['inventory-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#inventorytable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/inventory/ajax', { }, '#inventorytable', '#inventory-entry-template', '{{ trans('tool.Enter search keyword') }}', '', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 1, 'desc' ]],
					columnDefs : [{ orderable: false, targets: 4 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#inventorytable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['taccount-window'])
	<script type="text/javascript">
		$(document).ready(function() {
			$('#accttable').DataTable(Object.assign(
				dataTableDefaultConfig('{{ trans('forms.Refresh/Reload') }}', 'GET', '/dashboard/account/all/ajax', { }, '#accttable', '#taccount-entry-template', '{{ trans('tool.Enter search keyword') }}', '', {{ env('DATATABLE_DEFAULT_ROWS', 10) }}),
				{
					order : [[ 0, 'asc' ]],
					columnDefs : [{ orderable: false, targets: 4 }]
				}
			)).on('preXhr.dt', function(e, settings) {
				showDataTableProcessingTransient('#accttable');
			});
		} );
	</script>
@endif

@if ($controlSwitch['transactable-template'])
	<script type="text/javascript">
		function refreshTableWithTransactable(trx, is_new) {
			let content = populateHtmlTemplateWithData($("#transactable-table-template").html().toString(), trx);
			switch (trx['type']) {
				case 'receivable':
					if (!is_new && $('#receivabletable').DataTable().row('#transactable-' + trx['id']).length) {
						$('#receivabletable').DataTable().row('#transactable-' + trx['id']).remove();
					}
					$('#receivabletable').DataTable().row.add($(content)).draw();
					break;
				case 'payable':
					if (!is_new && $('#payabletable').DataTable().row('#transactable-' + trx['id']).length) {
						$('#payabletable').DataTable().row('#transactable-' + trx['id']).remove();
					}
					$('#payabletable').DataTable().row.add($(content)).draw();
					break;
				default:
					break;
			}
		}
	</script>
@endif

@if ($controlSwitch['entity-template'])
	<script type="text/javascript">
		function refreshTableWithEntity(entity, is_new) {
			let content = populateHtmlTemplateWithData($("#entity-table-template").html().toString(), entity);
			switch (entity['type']) {
				case 'customer':
					if (!is_new && $('#customertable').DataTable().row('#entity-' + entity['id']).length) {
						$('#customertable').DataTable().row('#entity-' + entity['id']).remove();
					}
					$('#customertable').DataTable().row.add($(content)).draw();
					break;
				default:
					if (!is_new && $('#suppliertable').DataTable().row('#entity-' + entity['id']).length) {
						$('#suppliertable').DataTable().row('#entity-' + entity['id']).remove();
					}
					$('#suppliertable').DataTable().row.add($(content)).draw();
					break;
			}
		}
	</script>
@endif

@if ($controlSwitch['expense-template'])
	<script type="text/javascript">
		function refreshTableWithCharge(charge, is_new) {
			let content = populateHtmlTemplateWithData($("#expense-table-template").html().toString(), charge);			if (!is_new && $('#chargetable').DataTable().row('#charge-' + charge['id']).length) {
				$('#chargetable').DataTable().row('#charge-' + charge['id']).remove();
			}
			$('#chargetable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['taccount-template'])
	<script type="text/javascript">
		function refreshTableWithTaccount(taccount, is_new) {
			let content = populateHtmlTemplateWithData($("#taccount-entry-template").html().toString(), taccount);
			if (!is_new && $('#accttable').DataTable().row('#taccount-' + taccount['id']).length) {
				$('#accttable').DataTable().row('#taccount-' + taccount['id']).remove();
			}
			$('#accttable').DataTable().row.add($(content)).draw();
		}
	</script>
@endif

@if ($controlSwitch['purchase-process-modal'])
	<script type="text/javascript">
		function vuePurchaseProcessDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// selection of supplying entities
			vuePurchaseProcessDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getPayableEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of payment terms
			vuePurchaseProcessDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of contact
			vuePurchaseProcessDataSource.selection_contact = {!! json_encode(\App\User::getUsersIndexedByEntity(['supplier'])) !!};
			// selection of staff
			vuePurchaseProcessDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of currency
			vuePurchaseProcessDataSource.selection_currency = {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of product
			vuePurchaseProcessDataSource.selection_product = {!! json_encode(\App\UniqueTradable::getProducts('sku', 'asc')->pluck('sku', 'id')->toArray()) !!};
			// selection of warehouse
			vuePurchaseProcessDataSource.selection_warehouse = {!! json_encode(\App\Location::getWarehouses('name', 'asc')->toArray()) !!};
			// button of 'Process'
			vuePurchaseProcessDataSource.button_process = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// text of 'Create payable'
			vuePurchaseProcessDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date('Y-m-d')) }}";
			// text of 'Create payable'
			vuePurchaseProcessDataSource.text_process_purchase_order = "{{ trans('finance.Create payable') }}";
			// text of 'Create payable'
			vuePurchaseProcessDataSource.text_process_purchase_return = "{{ trans('finance.Create payable credit') }}";
			// callback function when new payable is created
			vuePurchaseProcessDataSource.insertCallback = function(data) {
				refreshTableWithTransactable(data, true);
			};
			// since there's no purchase-order table, callback function not installed
		});
	</script>
@endif

@if ($controlSwitch['sales-process-modal'])
	<script type="text/javascript">
		function vueSalesProcessDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// selection of supplying entities
			vueSalesProcessDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getReceivableEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of payment terms
			vueSalesProcessDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of contact
			vueSalesProcessDataSource.selection_contact = {!! json_encode(\App\User::getUsersIndexedByEntity(['customer', 'supplier', 'employee'])) !!};
			// selection of staff
			vueSalesProcessDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of currency
			vueSalesProcessDataSource.selection_currency = {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of product
			vueSalesProcessDataSource.selection_product = {!! json_encode(\App\UniqueTradable::getProducts('sku', 'asc')->pluck('sku', 'id')->toArray()) !!};
			// selection of warehouse
			vueSalesProcessDataSource.selection_warehouse = {!! json_encode(\App\Location::getWarehouses('name', 'asc')->toArray()) !!};
			// button of 'Process'
			vueSalesProcessDataSource.button_process = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// text of 'Create payable'
			vueSalesProcessDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date('Y-m-d')) }}";
			// text of 'Create payable'
			vueSalesProcessDataSource.text_process_sales_order = "{{ trans('finance.Create receivable') }}";
			// text of 'Create payable'
			vueSalesProcessDataSource.text_process_sales_return = "{{ trans('finance.Create receivable credit') }}";
			// callback function when new receivable is created
			vueSalesProcessDataSource.insertCallback = function(data) {
				refreshTableWithTransactable(data, true);
			};
			// since there's no sales-order table, callback function is not installed
		});
	</script>
@endif

@if ($controlSwitch['transactable-modal'])
	<script type="text/javascript">
		function vueTransactableDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// selection of client entities
			vueTransactableDataSource.selection_receivable = {!! json_encode(\App\TaxableEntity::getReceivableEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of supplying entities
			vueTransactableDataSource.selection_payable = {!! json_encode(\App\TaxableEntity::getPayableEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of payment terms
			vueTransactableDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of contact
			vueTransactableDataSource.selection_contact = {!! json_encode(\App\User::getUsersIndexedByEntity(['supplier', 'customer'])) !!};
			// selection of staff
			vueTransactableDataSource.selection_staff = {!! json_encode(\App\User::getAllStaff('name', 'asc')->pluck('name', 'id')->toArray()) !!};
			// selection of currency
			vueTransactableDataSource.selection_currency = {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->pluck('symbol', 'id')->toArray()) !!};
			// selection of product
			vueTransactableDataSource.selection_item = {!! json_encode(\App\UniqueTradable::orderBy('sku', 'asc')->get()->pluck('sku', 'id')->toArray()) !!};
			// selection of billing-address
			vueTransactableDataSource.selection_billing = {!! json_encode(\App\Address::getAddressesIndexedByEntity(['supplier','customer', 'employee'], 'billing')) !!};
			// selection of shipping-address
			vueTransactableDataSource.selection_shipping = {!! json_encode(\App\Address::getAddressesIndexedByEntity(['supplier','customer', 'employee'], 'shipping')) !!};
			// button of 'View'
			vueTransactableDataSource.button_view = "<i class=\"fa fa-btn fa-file-pdf-o\"></i>" + "{{ trans('forms.View PDF') }}";
			// button of 'Void'
			vueTransactableDataSource.button_void = "<i class=\"fa fa-btn fa-ban\"></i>" + "{{ trans('forms.Void') }}";
			// text of 'View receivable'
			vueTransactableDataSource.text_view_receivable = "{{ trans('finance.View receivable') }}";
			// text of 'View payable'
			vueTransactableDataSource.text_view_payable = "{{ trans('finance.View payable') }}";
			// text of 'View receivable'
			vueTransactableDataSource.text_void_receivable = "{{ trans('finance.Void receivable') }}";
			// text of 'View payable'
			vueTransactableDataSource.text_void_payable = "{{ trans('finance.Void payable') }}";
			// callback function when new order is submitted
			vueTransactableDataSource.insertCallback = function(data) {
				refreshTableWithTransactable(data, true);
			};
			// callback function when order is updated
			vueTransactableDataSource.updateCallback = function(data) {
				refreshTableWithTransactable(data, false);
			};
		});
	</script>
@endif

@if ($controlSwitch['taxable-entity-modal'])
	<script type="text/javascript">
		function vueTaxableEntityDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text for button 'create'
			vueTaxableEntityDataSource.button_create = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// text for button 'update'
			vueTaxableEntityDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// selection of country location
			vueTaxableEntityDataSource.selection_country = {!! json_encode(\App\Helpers\CountryHelper::getAllCountryOptions()) !!};
			// selection of payment term
			vueTaxableEntityDataSource.selection_payment = {!! json_encode(\App\PaymentTerm::orderBy('grace_days', 'asc')->get()->mapWithKeys(function ($item) { return [ $item->id => [ 'symbol' => $item->symbol, 'description' => $item->description ]]; })->toArray()) !!};
			// selection of currency
			vueTaxableEntityDataSource.selection_currency =  {!! json_encode(\App\Currency::orderBy('symbol', 'asc')->get()->mapWithKeys(function ($item) { return [$item->id => [ 'symbol' => $item->symbol, 'description' => $item->description ]]; })->toArray()) !!};
			// text of 'Create supplier'
			vueTaxableEntityDataSource.text_create_supplier = "{{ trans('vrm.New supplier') }}";
			// text of 'Create customer'
			vueTaxableEntityDataSource.text_create_customer = "{{ trans('crm.New customer') }}";
			// text of 'Create employee'
			vueTaxableEntityDataSource.text_create_employee = "{{ trans('tool.Create new user') }}";
			// text of 'View supplier'
			vueTaxableEntityDataSource.text_view_supplier = "{{ trans('vrm.View supplier') }}";
			// text of 'View customer'
			vueTaxableEntityDataSource.text_view_customer = "{{ trans('crm.View customer') }}";
			// text of 'View employee'
			vueTaxableEntityDataSource.text_view_employee = "{{ trans('tool.Show user') }}";
			// text of 'Update supplier'
			vueTaxableEntityDataSource.text_update_supplier = "{{ trans('vrm.Update supplier') }}";
			// text of 'Update customer'
			vueTaxableEntityDataSource.text_update_customer = "{{ trans('crm.Update customer') }}";
			// text of 'Update employee'
			vueTaxableEntityDataSource.text_update_employee = "{{ trans('tool.Edit user') }}";
			// callback function when new entity is entered
			vueTaxableEntityDataSource.insertCallback = function(data) {
				refreshTableWithEntity(data, true);
			};
			// callback function when existing entity is updated
			vueTaxableEntityDataSource.updateCallback = function(data) {
				refreshTableWithEntity(data, false);
			};
		});
	</script>
@endif


@if ($controlSwitch['tradable-transaction-modal'])
	<script type="text/javascript">
		function vueTradableTransactionDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text for button 'create'
			vueTradableTransactionDataSource.button_load_more_transaction = "{{ trans('forms.Load more transactions') }}";
		});
	</script>
@endif

@if ($controlSwitch['taccount-transaction-modal'])
	<script type="text/javascript">
		function vueTaccountTransactionDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text for button 'create'
			vueTaccountTransactionDataSource.button_load_more_transaction = "{{ trans('forms.Load more transactions') }}";
		});
	</script>
@endif

@if ($controlSwitch['charge-entry-modal'])
	<script type="text/javascript">
		function vueChargeDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// boolean of OCR
			vueChargeDataSource.bool_ocr = "{{ \App\Helpers\ParameterHelper::getValue("charge_ocr") ?? false }}";
			// text of date of today
			vueChargeDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// default taxable entity id
			vueChargeDataSource.id_default_entity = {{ auth()->user()->entity->id }};
			// current user id
			vueChargeDataSource.id_current_user = {{ auth()->user()->id }};
			// text of 'browse file'
			vueChargeDataSource.text_browse_file = "{{ trans('tool.Browse file') }}";
			// text of 'attachment download failed'
			vueChargeDataSource.text_attachment_download_failed = "{{ trans('messages.Attachment download failed') }}";
			// text of 'upload file'
			vueChargeDataSource.text_upload_file = "{{ trans('tool.Upload file') }}";
			// text of 'view file'
			vueChargeDataSource.text_view_file = "{{ trans('tool.View file') }}";
			// text of 'new charge'
			vueChargeDataSource.text_new_charge = "{{ trans('finance.New charge') }}";
			// text of 'view charge'
			vueChargeDataSource.text_view_charge = "{{ trans('finance.View charge') }}";
			// text of 'update charge'
			vueChargeDataSource.text_update_charge = "{{ trans('finance.Update charge') }}";
			// text of 'submit charge'
			vueChargeDataSource.text_submit_charge = "{{ trans('finance.Submit charge') }}";
			// text of 'retract charge'
			vueChargeDataSource.text_retract_charge = "{{ trans('finance.Retract charge') }}";
			// text of 'approve charge'
			vueChargeDataSource.text_approve_charge = "{{ trans('finance.Approve charge') }}";
			// button of 'New charge'
			vueChargeDataSource.button_create = "<i class=\"fa fa-btn fa-floppy-o\"></i>" + "{{ trans('forms.Create') }}";
			// button of 'Update charge'
			vueChargeDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// button of 'Submit charge'
			vueChargeDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// button of 'Retract charge'
			vueChargeDataSource.button_retract = "<i class=\"fa fa-btn fa-times\"></i>" + "{{ trans('forms.Retract') }}";
			// button of 'Approve charge'
			vueChargeDataSource.button_approve = "<i class=\"fa fa-btn fa-check-square-o\"></i>" + "{{ trans('forms.Approve') }}";
			// button of 'disapprove charge'
			vueChargeDataSource.button_reject = "<i class=\"fa fa-btn fa-thumbs-o-down\"></i>" + "{{ trans('forms.Disapprove') }}";
			// selection of entity
			vueChargeDataSource.selection_entity = {!! json_encode(\App\TaxableEntity::getActiveEntities('code', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->code . '  (' . $item->name . ')' ]; })->toArray()) !!};
			// selection of staff
			vueChargeDataSource.selection_staff = {!! json_encode(\App\User::getActiveStaff('name', 'asc')->pluck('name', 'id')); !!};
			// selection of currency
			vueChargeDataSource.selection_currency = {!! json_encode(\App\Currency::getActiveCurrencies('symbol', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->symbol . '  (' . $item->description . ')' ]; })->toArray()); !!};
			// selection of expenditure item
			vueChargeDataSource.selection_item = {!! json_encode(\App\UniqueTradable::getActiveExpenditures('sku', 'asc')->pluck('sku', 'id')) !!};
			// callback function after update
			vueChargeDataSource.updateCallback = function (charge) {
				refreshTableWithCharge(charge, false);
			};
			// callback function after insert
			vueChargeDataSource.insertCallback = function (charge) {
				refreshTableWithCharge(charge, true);
			};
		});
	</script>
@endif

@if ($controlSwitch['taccount-form-modal'])
	<script type="text/javascript">
		function vueTaccountFormDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text of create account
			vueTaccountFormDataSource.text_create_account = "{{ trans('forms.Create chart-account') }}";
			// text of view account
			vueTaccountFormDataSource.text_view_account = "{{ trans('forms.View chart-account') }}";
			// text of update account
			vueTaccountFormDataSource.text_update_account = "{{ trans('forms.Edit chart-account') }}";
			// selection of account type
			vueTaccountFormDataSource.selection_type = {!! json_encode(\App\Helpers\ChartAccountHelper::allTypes()); !!};
			// selection of account currency
			vueTaccountFormDataSource.selection_currency = {!! json_encode(\App\Currency::getActiveCurrencies('symbol', 'asc')->mapWithKeys(function ($item) { return [ $item->id => $item->symbol . '  (' . $item->description . ')' ]; })->toArray()); !!};
			// button of submit
			vueTaccountFormDataSource.button_submit = "<i class=\"fa fa-btn fa-file-text\"></i>" + "{{ trans('forms.Submit') }}";
			// button of update
			vueTaccountFormDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// callback function after update
			vueTaccountFormDataSource.updateCallback = function (taccount) {
				refreshTableWithTaccount(taccount, false);
			};
			// callback function after insert
			vueTaccountFormDataSource.insertCallback = function (taccount) {
				refreshTableWithTaccount(taccount, true);
			};
		});
	</script>
@endif

@if (@controlSwitch['income-receipt-modal'])
	<script type="text/javascript">
		function vueIncomeReceiptDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text to today
			vueIncomeReceiptDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// text to modal title
			vueIncomeReceiptDataSource.text_title = "{{ trans('forms.Receive payment') }}";
			// text of 'must select an account' error messages
			vueIncomeReceiptDataSource.text_select_a_bank_account = "{{ trans('finance.Must select an account') }}";
			// text of 'must between ? and ?' error messages
			vueIncomeReceiptDataSource.text_not_greater_than_balance = "{{ trans('finance.Must not greater than balance') }}";
			// text of error messages
			vueIncomeReceiptDataSource.text_not_enough_credit = "{{ trans('finance.Not enough credit') }}";
			// button of "Update"
			vueIncomeReceiptDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// selection of bank account
			vueIncomeReceiptDataSource.selection_bank_account = {!! json_encode(\App\ChartAccount::find(unserialize(\App\Parameter::where('key', 'bank_cash_t_account_ids')->first()->value))->mapWithKeys(function ($item) { return [ $item->id => $item->description ]; })) !!};
			// callback function after update
			vueIncomeReceiptDataSource.updateCallback = function (data) {
				// update customer table
				refreshTableWithEntity(data['entity'], false);
				// update receivable table
				for (id in data['receivables']) {
					refreshTableWithTransactable(data['receivables'][id], false);
				}
			}
		});
	</script>
@endif

@if ($controlSwitch['payment-disbursement-modal'])
	<script type="text/javascript">
		function vuePaymentExpenditureDataSource() {
			// function that holds global variables
		}

		$(document).ready(function() {
			// text to today
			vuePaymentExpenditureDataSource.text_today = "{{ \App\Helpers\DateHelper::dbToGuiDate(date("Y-m-d")) }}";
			// text to modal title
			vuePaymentExpenditureDataSource.text_title = "{{ trans('forms.Issue payment') }}";
			// text of 'must select an account' error messages
			vuePaymentExpenditureDataSource.text_select_a_bank_account = "{{ trans('finance.Must select an account') }}";
			// text of 'must between ? and ?' error messages
			vuePaymentExpenditureDataSource.text_not_greater_than_balance = "{{ trans('finance.Must not greater than balance') }}";
			// button of "Update"
			vuePaymentExpenditureDataSource.button_update = "<i class=\"fa fa-btn fa-pencil-square-o\"></i>" + "{{ trans('forms.Update') }}";
			// selection of bank account
			vuePaymentExpenditureDataSource.selection_bank_account = {!! json_encode(\App\ChartAccount::find(array_merge(unserialize(\App\Parameter::where('key', 'bank_cash_t_account_ids')->first()->value), unserialize(\App\Parameter::where('key', 'credit_card_t_account_ids')->first()->value)))->mapWithKeys(function ($item) { return [ $item->id => $item->description ]; })) !!};
			// callback function after update
			vuePaymentExpenditureDataSource.updateCallback = function (data) {
				// update customer table
				refreshTableWithEntity(data['entity'], false);
				// update receivable table
				for (id in data['payables']) {
					refreshTableWithTransactable(data['payables'][id], false);
				}
			}
		});
	</script>
@endif

@if ($controlSwitch['transactable-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/transactable_form.js') }}"></script>
@endif

@if ($controlSwitch['purchase-process-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/purchase_process.js') }}"></script>
@endif

@if ($controlSwitch['sales-process-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/sales_process.js') }}"></script>
@endif

@if ($controlSwitch['taxable-entity-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/taxable_entity.js') }}"></script>
@endif

@if ($controlSwitch['tradable-transaction-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/tradable_transaction.js') }}"></script>
@endif

@if ($controlSwitch['taccount-transaction-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/taccount_transaction.js') }}"></script>
@endif

@if ($controlSwitch['charge-entry-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/charge_entry.js') }}"></script>
@endif

@if ($controlSwitch['taccount-form-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/taccount_form.js') }}"></script>
@endif

@if ($controlSwitch['income-receipt-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/income_form.js') }}"></script>
@endif

@if ($controlSwitch['payment-disbursement-modal'])
	<script type="text/javascript" src="{{ asset('js/embedded_modal/payment_form.js') }}"></script>
@endif

@endsection
